//! Decode only the event layout generated by the original executing Wasm.
//! Callsite labels remain unapproved references; absent refund evidence stays
//! unknown. These candidate facts do not admit a runtime or a finalized block.

use super::{hex_bytes, observer::Observation, scale_exact};
use crate::ProbeError;
use frame_metadata::{RuntimeMetadata, RuntimeMetadataPrefixed, META_RESERVED};
use parity_scale_codec::{Compact, Decode, Encode};
use scale_info::{form::PortableForm, PortableRegistry, TypeDef, TypeDefPrimitive, Variant};
use serde::{Deserialize, Serialize};
use sp_core::hashing::{blake2_256, sha2_256, twox_128};
use std::collections::BTreeSet;

const MAXIMUM_METADATA: usize = 2 * 1024 * 1024;
const MAXIMUM_EVENT: usize = 1024 * 1024;

/// The callsite trace is the evidence source; a caller cannot supply decoded
/// event fields in place of these exact runtime-generated layouts.
pub(super) struct EventLayout {
    pub(super) metadata_sha256: [u8; 32],
    types: PortableRegistry,
    balance_pallet: u8,
    withdraw: u8,
    deposit: u8,
    ethereum_pallet: u8,
    executed: u8,
    exit_reason: u32,
    extra_data: u32,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FeeEvent {
    pub observation_ordinal: usize,
    pub purpose: String,
    pub phase: String,
    pub extrinsic_index: Option<u32>,
    pub event: String,
    pub payer: Option<[u8; 32]>,
    pub amount_rao: Option<String>,
    pub source: Option<[u8; 20]>,
    pub transaction_hash: Option<[u8; 32]>,
    pub event_sha256: [u8; 32],
}

/// A present zero refund requires an actual zero Deposit record. It is never
/// synthesized from a missing event, requested amount, balance or receipt gas.
#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FeeCandidate {
    pub transaction_hash: [u8; 32],
    pub payer: [u8; 32],
    pub extrinsic_index: Option<u32>,
    pub withdrawal_rao: Option<String>,
    pub refund_rao: Option<String>,
    pub debit_rao: Option<String>,
    pub status: String,
    pub event_ordinals: Vec<usize>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FeeEventReport {
    pub metadata_sha256: [u8; 32],
    pub authority: String,
    pub events: Vec<FeeEvent>,
    pub candidates: Vec<FeeCandidate>,
    pub unmatched_fee_events: usize,
}

fn refuse(message: &str) -> ProbeError {
    ProbeError::new(format!("historical fee event {message}"))
}

fn variant(
    types: &PortableRegistry,
    ty: u32,
    name: &str,
) -> Result<Variant<PortableForm>, ProbeError> {
    let TypeDef::Variant(value) = &types
        .resolve(ty)
        .ok_or_else(|| refuse("type absent"))?
        .type_def
    else {
        return Err(refuse("event is not a variant"));
    };
    let mut names = BTreeSet::new();
    let mut indices = BTreeSet::new();
    for entry in &value.variants {
        if !names.insert(&entry.name) || !indices.insert(entry.index) {
            return Err(refuse("ambiguous variant identity"));
        }
    }
    value
        .variants
        .iter()
        .find(|entry| entry.name == name)
        .cloned()
        .ok_or_else(|| refuse("named event absent"))
}

/// Newtypes may wrap an exact byte array or u64, but compact numbers, altered
/// integer widths and extra fields cannot silently change economic units.
fn fixed_shape(types: &PortableRegistry, ty: u32, bytes: Option<u32>, depth: usize) -> bool {
    if depth > 16 {
        return false;
    }
    let Some(value) = types.resolve(ty) else {
        return false;
    };
    match &value.type_def {
        TypeDef::Composite(value) if value.fields.len() == 1 => {
            fixed_shape(types, value.fields[0].ty.id, bytes, depth + 1)
        }
        TypeDef::Tuple(value) if value.fields.len() == 1 => {
            fixed_shape(types, value.fields[0].id, bytes, depth + 1)
        }
        TypeDef::Array(value) if bytes == Some(value.len) => matches!(
            types.resolve(value.type_param.id).map(|v| &v.type_def),
            Some(TypeDef::Primitive(TypeDefPrimitive::U8))
        ),
        TypeDef::Primitive(TypeDefPrimitive::U64) => bytes.is_none(),
        _ => false,
    }
}

impl EventLayout {
    /// This input is returned by Metadata_metadata on the same original code,
    /// with no storage/offchain hosts. The expected digest is an additional pin.
    pub(super) fn from_generated(raw: &[u8], expected: [u8; 32]) -> Result<Self, ProbeError> {
        if raw.len() > MAXIMUM_METADATA || expected == [0; 32] || sha2_256(raw) != expected {
            return Err(refuse("runtime-generated metadata pin or bound differs"));
        }
        let metadata: RuntimeMetadataPrefixed = scale_exact("generated fee metadata", raw)?;
        if metadata.0 != META_RESERVED {
            return Err(refuse("metadata prefix differs"));
        }
        let (types, pallets): (PortableRegistry, Vec<(String, u8, Option<u32>)>) = match metadata.1
        {
            RuntimeMetadata::V14(value) => (
                value.types,
                value
                    .pallets
                    .into_iter()
                    .map(|p| (p.name, p.index, p.event.map(|v| v.ty.id)))
                    .collect(),
            ),
            RuntimeMetadata::V15(value) => (
                value.types,
                value
                    .pallets
                    .into_iter()
                    .map(|p| (p.name, p.index, p.event.map(|v| v.ty.id)))
                    .collect(),
            ),
            _ => return Err(refuse("metadata version unsupported")),
        };
        if types.types.len() > 16384
            || pallets.len() > 256
            || types
                .types
                .iter()
                .enumerate()
                .any(|(index, value)| value.id as usize != index)
        {
            return Err(refuse("metadata registry bound or identity differs"));
        }
        let mut names = BTreeSet::new();
        let mut indices = BTreeSet::new();
        for (name, index, _) in &pallets {
            if !names.insert(name) || !indices.insert(index) {
                return Err(refuse("ambiguous pallet identity"));
            }
        }
        let find = |name: &str| -> Result<(u8, u32), ProbeError> {
            let (_, index, ty) = pallets
                .iter()
                .find(|(n, _, _)| n == name)
                .ok_or_else(|| refuse("pallet absent"))?;
            Ok((*index, ty.ok_or_else(|| refuse("pallet events absent"))?))
        };
        let (balance_pallet, balance_type) = find("Balances")?;
        let (ethereum_pallet, ethereum_type) = find("Ethereum")?;
        let withdraw = variant(&types, balance_type, "Withdraw")?;
        let deposit = variant(&types, balance_type, "Deposit")?;
        for entry in [&withdraw, &deposit] {
            if entry.fields.len() != 2
                || entry.fields[0].name.as_deref() != Some("who")
                || entry.fields[1].name.as_deref() != Some("amount")
                || !fixed_shape(&types, entry.fields[0].ty.id, Some(32), 0)
                || !fixed_shape(&types, entry.fields[1].ty.id, None, 0)
            {
                return Err(refuse("native payer or amount layout differs"));
            }
        }
        let executed = variant(&types, ethereum_type, "Executed")?;
        let expected_names = [
            "from",
            "to",
            "transaction_hash",
            "exit_reason",
            "extra_data",
        ];
        if executed.fields.len() != expected_names.len()
            || executed
                .fields
                .iter()
                .zip(expected_names)
                .any(|(field, name)| field.name.as_deref() != Some(name))
            || !fixed_shape(&types, executed.fields[0].ty.id, Some(20), 0)
            || !fixed_shape(&types, executed.fields[1].ty.id, Some(20), 0)
            || !fixed_shape(&types, executed.fields[2].ty.id, Some(32), 0)
        {
            return Err(refuse("Ethereum execution layout differs"));
        }
        Ok(Self {
            metadata_sha256: expected,
            types,
            balance_pallet,
            withdraw: withdraw.index,
            deposit: deposit.index,
            ethereum_pallet,
            executed: executed.index,
            exit_reason: executed.fields[3].ty.id,
            extra_data: executed.fields[4].ty.id,
        })
    }

    pub(super) fn decode(
        &self,
        observations: &[Observation],
        extrinsics: usize,
    ) -> Result<FeeEventReport, ProbeError> {
        let mut key = twox_128(b"System").to_vec();
        key.extend(twox_128(b"Events"));
        let key = format!("0x{}", hex::encode(key));
        let mut events = Vec::new();
        for observation in observations {
            // Native profiles also retain original allocation/event appends.
            // Their complete records remain in the trace; only independently
            // selected fee callsites enter this metadata-specific decoder.
            if !matches!(
                observation.purpose.as_str(),
                "fee-withdraw" | "fee-refund" | "ethereum-executed"
            ) {
                continue;
            }
            if observation.key_hex != key || observation.operation != "append" {
                continue;
            }
            let value = observation
                .value_hex
                .as_ref()
                .ok_or_else(|| refuse("append value absent"))?;
            let raw = hex_bytes("fee event append", value, MAXIMUM_EVENT)?;
            let mut input = raw.as_slice();
            let (phase, extrinsic_index) = match take::<1>(&mut input)?[0] {
                0 => {
                    let index = u32::from_le_bytes(take(&mut input)?);
                    if index as usize >= extrinsics {
                        return Err(refuse("extrinsic placement exceeds complete body"));
                    }
                    ("apply-extrinsic", Some(index))
                }
                1 => ("finalization", None),
                2 => ("initialization", None),
                _ => return Err(refuse("phase differs")),
            };
            let pallet = take::<1>(&mut input)?[0];
            let event = take::<1>(&mut input)?[0];
            let mut decoded = FeeEvent {
                observation_ordinal: observation.ordinal,
                purpose: observation.purpose.clone(),
                phase: phase.to_owned(),
                extrinsic_index,
                event: String::new(),
                payer: None,
                amount_rao: None,
                source: None,
                transaction_hash: None,
                event_sha256: sha2_256(&raw),
            };
            if pallet == self.balance_pallet && (event == self.withdraw || event == self.deposit) {
                let (name, purpose) = if event == self.withdraw {
                    ("Balances.Withdraw", "fee-withdraw")
                } else {
                    ("Balances.Deposit", "fee-refund")
                };
                if observation.purpose != purpose {
                    return Err(refuse(
                        "balance event contradicts original callsite purpose",
                    ));
                }
                decoded.event = name.to_owned();
                decoded.payer = Some(take(&mut input)?);
                decoded.amount_rao = Some(u64::from_le_bytes(take(&mut input)?).to_string());
            } else if pallet == self.ethereum_pallet && event == self.executed {
                if observation.purpose != "ethereum-executed" {
                    return Err(refuse(
                        "execution event contradicts original callsite purpose",
                    ));
                }
                decoded.event = "Ethereum.Executed".to_owned();
                decoded.source = Some(take(&mut input)?);
                let _to = take::<20>(&mut input)?;
                decoded.transaction_hash = Some(take(&mut input)?);
                let mut work = 0;
                skip(&self.types, self.exit_reason, &mut input, 0, &mut work)?;
                skip(&self.types, self.extra_data, &mut input, 0, &mut work)?;
            } else {
                return Err(refuse(
                    "selected event is not the declared fee/execution variant",
                ));
            }
            let topics = compact(&mut input)?;
            if topics > 64 || input.len() != topics as usize * 32 {
                return Err(refuse("topics or trailing bytes differ"));
            }
            events.push(decoded);
        }
        let mut pending = Vec::<&FeeEvent>::new();
        let mut candidates = Vec::new();
        let mut transactions = BTreeSet::new();
        for event in &events {
            if event.event != "Ethereum.Executed" {
                pending.push(event);
                continue;
            }
            let source = event
                .source
                .ok_or_else(|| refuse("execution source absent"))?;
            let transaction_hash = event
                .transaction_hash
                .ok_or_else(|| refuse("execution identity absent"))?;
            if !transactions.insert(transaction_hash) {
                return Err(refuse("duplicate execution transaction"));
            }
            let mut mapping = b"evm:".to_vec();
            mapping.extend(source);
            let payer = blake2_256(&mapping);
            let mut withdrawal = None;
            let mut refund = None;
            let mut ordinals = Vec::new();
            let mut retained = Vec::new();
            for observed in pending.drain(..) {
                if observed.extrinsic_index != event.extrinsic_index
                    || event.extrinsic_index.is_none()
                {
                    retained.push(observed);
                    continue;
                }
                if observed.payer != Some(payer) {
                    return Err(refuse("payer differs from executed H160 mapping"));
                }
                let amount = observed
                    .amount_rao
                    .as_ref()
                    .ok_or_else(|| refuse("native amount absent"))?
                    .parse::<u64>()
                    .map_err(|_| refuse("native amount overflow"))?;
                let prior = if observed.event == "Balances.Withdraw" {
                    if refund.is_some() {
                        return Err(refuse("refund precedes withdrawal"));
                    }
                    withdrawal.replace(amount)
                } else {
                    refund.replace(amount)
                };
                if prior.is_some() {
                    return Err(refuse(
                        "multiple fee effects cannot be assigned to one execution",
                    ));
                }
                ordinals.push(observed.observation_ordinal);
            }
            pending = retained;
            ordinals.push(event.observation_ordinal);
            let (debit, status) = match (event.extrinsic_index, withdrawal, refund) {
                (None, _, _) => (None, "placement-unresolved"),
                (_, Some(w), Some(r)) if r <= w => {
                    (Some((w - r).to_string()), "observed-pair-unadmitted")
                }
                (_, Some(_), Some(_)) => {
                    return Err(refuse("actual refund exceeds actual withdrawal"))
                }
                (_, None, _) => (None, "withdrawal-unobserved"),
                _ => (None, "refund-unobserved"),
            };
            candidates.push(FeeCandidate {
                transaction_hash,
                payer,
                extrinsic_index: event.extrinsic_index,
                withdrawal_rao: withdrawal.map(|v| v.to_string()),
                refund_rao: refund.map(|v| v.to_string()),
                debit_rao: debit,
                status: status.to_owned(),
                event_ordinals: ordinals,
            });
        }
        Ok(FeeEventReport {
            metadata_sha256: self.metadata_sha256,
            authority: "original-runtime-metadata-and-unapproved-callsite-profile".to_owned(),
            unmatched_fee_events: pending.len(),
            events,
            candidates,
        })
    }
}

fn take<const N: usize>(input: &mut &[u8]) -> Result<[u8; N], ProbeError> {
    if input.len() < N {
        return Err(refuse("truncated event"));
    }
    let (value, rest) = input.split_at(N);
    *input = rest;
    Ok(value.try_into().expect("fixed slice length"))
}

fn compact(input: &mut &[u8]) -> Result<u32, ProbeError> {
    let original = *input;
    let value = Compact::<u32>::decode(input).map_err(|_| refuse("compact length differs"))?;
    if value.encode() != original[..original.len() - input.len()] {
        return Err(refuse("noncanonical compact length"));
    }
    Ok(value.0)
}

/// Only event auxiliary fields use this bounded metadata walk. Fee amount and
/// payer fields use the explicit fixed-width checks above, never heuristics.
fn skip(
    types: &PortableRegistry,
    ty: u32,
    input: &mut &[u8],
    depth: usize,
    work: &mut usize,
) -> Result<(), ProbeError> {
    *work += 1;
    if depth > 32 || *work > 16384 {
        return Err(refuse("auxiliary decode work bound"));
    }
    let definition = &types
        .resolve(ty)
        .ok_or_else(|| refuse("auxiliary type absent"))?
        .type_def;
    match definition {
        TypeDef::Composite(value) => {
            for field in &value.fields {
                skip(types, field.ty.id, input, depth + 1, work)?;
            }
        }
        TypeDef::Tuple(value) => {
            for field in &value.fields {
                skip(types, field.id, input, depth + 1, work)?;
            }
        }
        TypeDef::Variant(value) => {
            let index = take::<1>(input)?[0];
            let selected: Vec<_> = value.variants.iter().filter(|v| v.index == index).collect();
            if selected.len() != 1 {
                return Err(refuse("auxiliary variant identity differs"));
            }
            for field in &selected[0].fields {
                skip(types, field.ty.id, input, depth + 1, work)?;
            }
        }
        TypeDef::Sequence(value) => {
            let count = compact(input)?;
            if count > 4096 {
                return Err(refuse("auxiliary sequence bound"));
            }
            for _ in 0..count {
                skip(types, value.type_param.id, input, depth + 1, work)?;
            }
        }
        TypeDef::Array(value) => {
            if value.len > 4096 {
                return Err(refuse("auxiliary array bound"));
            }
            for _ in 0..value.len {
                skip(types, value.type_param.id, input, depth + 1, work)?;
            }
        }
        TypeDef::Primitive(value) => {
            let length = match value {
                TypeDefPrimitive::Bool => {
                    let value = take::<1>(input)?[0];
                    if value > 1 {
                        return Err(refuse("boolean differs"));
                    }
                    return Ok(());
                }
                TypeDefPrimitive::U8 | TypeDefPrimitive::I8 => 1,
                TypeDefPrimitive::U16 | TypeDefPrimitive::I16 => 2,
                TypeDefPrimitive::U32 | TypeDefPrimitive::I32 => 4,
                TypeDefPrimitive::U64 | TypeDefPrimitive::I64 => 8,
                TypeDefPrimitive::U128 | TypeDefPrimitive::I128 => 16,
                TypeDefPrimitive::U256 | TypeDefPrimitive::I256 => 32,
                TypeDefPrimitive::Str => {
                    let count = compact(input)? as usize;
                    if count > 4096
                        || input.len() < count
                        || std::str::from_utf8(&input[..count]).is_err()
                    {
                        return Err(refuse("string bound or encoding differs"));
                    }
                    *input = &input[count..];
                    return Ok(());
                }
                _ => return Err(refuse("auxiliary primitive unsupported")),
            };
            if input.len() < length {
                return Err(refuse("auxiliary value truncated"));
            }
            *input = &input[length..];
        }
        _ => return Err(refuse("auxiliary compact or bit layout unsupported")),
    }
    Ok(())
}
