// Synthetic independent keys exercise additive authority and selection without
// granting any current observation or file a production send capability.
package main

import (
	"bytes"
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/urfoundation/sn/v2026/crv4"
)

// Every new revision uses separate private artifact-review evidence. Synthetic
// signatures are never generated by the production runtime import path.
func bootstrapSuccessorRuntimeTestApproval(t *testing.T, plan bootstrapSuccessorExecutionPlan, base bootstrapSuccessorCanonicalApproval, key ed25519.PrivateKey, previous []bootstrapSuccessorRuntimeApproval, profile rootReceiptProfile) bootstrapSuccessorRuntimeApproval {
	t.Helper()
	predecessor := rootObjectHash(base)
	if len(previous) != 0 {
		predecessor = rootObjectHash(previous[len(previous)-1])
	}
	authorization := bootstrapSuccessorRuntimeAuthorization{Schema: bootstrapSuccessorRuntimeSchema, ExecutionPlanHash: plan.hash(), CanonicalAuthorityHash: rootObjectHash(base),
		Sequence: uint16(len(previous) + 1), PreviousHash: predecessor, Runtime: profile, Policy: bootstrapSuccessorRuntimePolicy,
		RuntimeEvidence: bootstrapSuccessorExecutionTestRaw(t, "synthetic-additive-runtime-review.txt", []byte("synthetic independent artifact/build and existing codec review"))}
	return bootstrapSuccessorRuntimeTestSign(t, authorization, key)
}

// Sign the literal canonical test payload, including deliberately invalid
// fields, so structural refusals cannot hide behind a stale signature.
func bootstrapSuccessorRuntimeTestSign(t *testing.T, authorization bootstrapSuccessorRuntimeAuthorization, key ed25519.PrivateKey) bootstrapSuccessorRuntimeApproval {
	t.Helper()
	raw, err := json.Marshal(authorization)
	if err != nil {
		t.Fatal(err)
	}
	return bootstrapSuccessorRuntimeApproval{Authorization: authorization, Signature: hex.EncodeToString(ed25519.Sign(key, append([]byte(bootstrapSuccessorRuntimeDomain+"\x00"), raw...)))}
}

// New scope, evidence and domain require the original independent signer.
func TestBootstrapSuccessorRuntimeRevisionIndependentAuthority(t *testing.T) {
	f := newBootstrapSuccessorExecutionFixture(t)
	base := bootstrapSuccessorCanonicalTestApproval(t, f.approval.Plan, f.key, bootstrapSuccessorCanonicalTestRuntime())
	profile := base.Authorization.CurrentRuntime
	profile.RuntimeVersion.SpecVersion++
	revision := bootstrapSuccessorRuntimeTestApproval(t, f.approval.Plan, base, f.key, nil, profile)
	if err := revision.validate(t.Context(), f.approval.Plan, base); err != nil {
		t.Fatal("positive independent runtime revision", err)
	}
	if err := revision.extends(base, nil); err != nil {
		t.Fatal(err)
	}
	for _, signature := range []string{f.approval.Signature, base.Signature, strings.Repeat("00", 64), hex.EncodeToString(ed25519.Sign(ed25519.NewKeyFromSeed(bytes.Repeat([]byte{73}, 32)), []byte("synthetic other signer")))} {
		changed := revision
		changed.Signature = signature
		if err := changed.validate(t.Context(), f.approval.Plan, base); err == nil {
			t.Fatal("runtime revision accepted a foreign signature or signing domain")
		}
	}
	for _, c := range []struct {
		name   string
		mutate func(*bootstrapSuccessorRuntimeAuthorization)
	}{
		{name: "execution", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) {
			a.ExecutionPlanHash = rootObjectHash("synthetic other execution")
		}},
		{name: "base", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) {
			a.CanonicalAuthorityHash = rootObjectHash("synthetic other base")
		}},
		{name: "policy", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) {
			a.Policy = "renew-attempts-and-clear-original-authority"
		}},
		{name: "codec", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) {
			a.Runtime.RuntimeSourceCommit = "synthetic-unreviewed-codec"
		}},
		{name: "sequence zero", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) { a.Sequence = 0 }},
		{name: "evidence pin", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) {
			a.RuntimeEvidence.Sha256 = rootObjectHash("synthetic wrong pin")
		}},
		{name: "evidence overlap", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) {
			a.RuntimeEvidence = base.Authorization.RuntimeEvidence
		}},
	} {
		changed := revision.Authorization
		c.mutate(&changed)
		if err := bootstrapSuccessorRuntimeTestSign(t, changed, f.key).validate(t.Context(), f.approval.Plan, base); err == nil {
			t.Fatal("runtime revision accepted independently signed invalid scope", c.name)
		}
	}
	for _, c := range []struct {
		name   string
		mutate func(*bootstrapSuccessorRuntimeAuthorization)
	}{
		{name: "predecessor", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) { a.PreviousHash = rootObjectHash("synthetic fork") }},
		{name: "gap", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) { a.Sequence++ }},
		{name: "duplicate", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) { a.Runtime = base.Authorization.CurrentRuntime }},
		{name: "same-version changed code", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) {
			a.Runtime = base.Authorization.CurrentRuntime
			a.Runtime.RuntimeCodeHash = (common.Hash{1}).Hex()
		}},
		{name: "same-version changed metadata", mutate: func(a *bootstrapSuccessorRuntimeAuthorization) {
			a.Runtime = base.Authorization.CurrentRuntime
			a.Runtime.RuntimeMetadataHash = (common.Hash{1}).Hex()
		}},
	} {
		changed := revision.Authorization
		c.mutate(&changed)
		candidate := bootstrapSuccessorRuntimeTestSign(t, changed, f.key)
		if err := candidate.validate(t.Context(), f.approval.Plan, base); err != nil {
			t.Fatal("synthetic signed fork did not reach chain admission", c.name, err)
		}
		if err := candidate.extends(base, nil); err == nil {
			t.Fatal("runtime revision accepted a fork, gap or incompatible artifact", c.name)
		}
	}
	if err := os.WriteFile(revision.Authorization.RuntimeEvidence.Path, []byte("synthetic swapped review"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := revision.validate(t.Context(), f.approval.Plan, base); err == nil {
		t.Fatal("runtime revision accepted changed independent evidence")
	}
}

// This literal is the prior event wire format, hashed independently of the Go
// event encoder. Adding an omitted revision must preserve its exact old seal.
func TestBootstrapSuccessorRuntimeRevisionPreservesLegacyEventEncoding(t *testing.T) {
	const legacy = `{"schema":"urnetwork-mainnet-successor-execution-event-v1","approval_hash":"sha256:1111111111111111111111111111111111111111111111111111111111111111","sequence":1,"previous_hash":"sha256:2222222222222222222222222222222222222222222222222222222222222222","phase":"attempt-reserved","cumulative_attempts":9,"reserved_lifetime_wei":"1200000","canonical_authority_hash":"sha256:3333333333333333333333333333333333333333333333333333333333333333","content_hash":""}`
	var event bootstrapSuccessorExecutionEvent
	if err := decodePlanJson([]byte(legacy), &event); err != nil {
		t.Fatal(err)
	}
	raw, err := json.Marshal(event)
	if err != nil || string(raw) != legacy || rootObjectHash(event) != "sha256:0f64db9a707cfee973e13efc48b2241c09c482de090ba173d91f50ba53ca7a84" || event.RuntimeRevisionHash != "" {
		t.Fatal("additive runtime field changed legacy counted-event bytes or seal", err)
	}
}

// Thirteen retained profiles select at most two per read, without discarding
// an earlier artifact or making a node-reported version sufficient authority.
func TestBootstrapSuccessorRuntimeRevisionSelectsHistoricalPair(t *testing.T) {
	var profiles []rootReceiptProfile
	for i := range 13 {
		profile := bootstrapSuccessorCanonicalTestRuntime()
		profile.RuntimeVersion.SpecVersion += uint32(i)
		profile.RuntimeCodeHash = common.Hash{31: byte(i + 1)}.Hex()
		profile.RuntimeMetadataHash = common.Hash{30: byte(i + 1)}.Hex()
		profiles = append(profiles, profile)
	}
	for _, pair := range [][2]int{{12, 0}, {1, 11}, {0, 0}} {
		artifacts, err := bootstrapSuccessorRuntimeArtifactPair(profiles, profiles[pair[0]].RuntimeVersion, profiles[pair[1]].RuntimeVersion)
		want := 2
		if pair[0] == pair[1] {
			want = 1
		}
		if err != nil || len(artifacts) != want {
			t.Fatal("runtime history was capped or historical parent was lost", pair, artifacts, err)
		}
		for i, artifact := range artifacts {
			profile := profiles[pair[i]]
			if artifact != (crv4.RuntimeArtifactIdentity{Version: profile.RuntimeVersion, CodeHash: profile.RuntimeCodeHash, MetadataHash: profile.RuntimeMetadataHash}) {
				t.Fatal("historical selection changed exact artifact authority")
			}
		}
	}
	unapproved := profiles[12].RuntimeVersion
	unapproved.SpecVersion++
	if _, err := bootstrapSuccessorRuntimeArtifactPair(profiles, profiles[0].RuntimeVersion, unapproved); err == nil {
		t.Fatal("historical selection approved an unknown parent runtime")
	}
	duplicate := profiles[0]
	duplicate.RuntimeCodeHash = (common.Hash{7}).Hex()
	if _, err := bootstrapSuccessorRuntimeArtifactPair(append(profiles, duplicate), profiles[0].RuntimeVersion, profiles[1].RuntimeVersion); err == nil {
		t.Fatal("historical selection guessed between conflicting same-version artifacts")
	}
}

// The full observed artifact must match a retained profile. A correct version
// alone cannot cover changed code or metadata, including an approved predecessor.
func TestBootstrapSuccessorRuntimeRevisionCurrentArtifactAdmission(t *testing.T) {
	adapter, _, fixture := bootstrapSuccessorCanonicalSafeFixture(t)
	profile := fixture.config.Plan.Runtime
	adapter.runtimeProfiles = []rootReceiptProfile{bootstrapSuccessorCanonicalTestRuntime(), profile}
	head, err := adapter.chain.client.readIdentity(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if err := adapter.currentRuntime(t.Context(), head); err != nil {
		t.Fatal("approved current artifact from retained history was refused", err)
	}
	for _, field := range []string{"code", "metadata", "version"} {
		changed := profile
		switch field {
		case "code":
			changed.RuntimeCodeHash = (common.Hash{9}).Hex()
		case "metadata":
			changed.RuntimeMetadataHash = (common.Hash{9}).Hex()
		case "version":
			changed.RuntimeVersion.SpecVersion++
		}
		adapter.runtimeProfiles = []rootReceiptProfile{changed}
		if err := adapter.currentRuntime(t.Context(), head); err == nil {
			t.Fatal("runtime admission accepted incomplete artifact identity", field)
		}
	}
}
