// Native SDK qualification is opt-in because it executes an independently
// built extension. Only LedgerDevice is substituted; loading, RFC78 digest and
// proof generation use the reviewed artifact. No fixture opens USB or RPC.
package main

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/centrifuge/go-substrate-rpc-client/v4/types"
	"github.com/centrifuge/go-substrate-rpc-client/v4/types/codec"
)

type ownerSigningNativeSdkFixture struct {
	config ownerSigningDeviceConfig
	input  ownerSigningAdapterInput
	proof  []byte
	jsTail []byte
}

// These are the source-controlled localnet vectors at the exact SDK commit.
// Fixture content is loaded from that external checkout, never a chain. The
// device identity is generated by ownerSigningTestKey, not copied from it.
func newOwnerSigningNativeSdkFixture(t *testing.T) ownerSigningNativeSdkFixture {
	t.Helper()
	backendPath := os.Getenv("SN_OWNER_LEDGER_BACKEND")
	backendHash := os.Getenv("SN_OWNER_LEDGER_BACKEND_SHA256")
	sourcePath := os.Getenv("SN_OWNER_LEDGER_SDK_SOURCE")
	pythonPath := os.Getenv("SN_OWNER_LEDGER_PYTHON")
	if backendPath == "" && backendHash == "" && sourcePath == "" && pythonPath == "" {
		t.Skip("native SDK qualification requires the sealed artifact, source and Python environment")
	}
	if !bootstrapRootAbsolutePath(backendPath) || !bootstrapRootAbsolutePath(sourcePath) || !bootstrapRootAbsolutePath(pythonPath) || !planSha256(backendHash) {
		t.Fatal("all four SN_OWNER_LEDGER qualification pins must be explicit")
	}
	readPinned := func(name, expected string) []byte {
		raw, err := os.ReadFile(filepath.Join(sourcePath, name))
		if err != nil {
			t.Fatal(err)
		}
		digest := sha256.Sum256(raw)
		if hex.EncodeToString(digest[:]) != expected {
			t.Fatal("upstream fixture does not match pinned SDK commit", name)
		}
		return raw
	}
	var golden struct {
		Metadata struct {
			V15Hex string `json:"v15_hex"`
		} `json:"metadata"`
	}
	if err := json.Unmarshal(readPinned("sdk/python/tests/fixtures/golden.json", "3d7f407a238d7737336b082e97236b0ab7504803ebc87017c06d030d3c68a934"), &golden); err != nil {
		t.Fatal(err)
	}
	var wrapped types.OptionBytes
	if err := codec.DecodeFromHex(golden.Metadata.V15Hex, &wrapped); err != nil {
		t.Fatal(err)
	}
	set, metadata := wrapped.Unwrap()
	if !set || len(metadata) < 5 || !bytes.Equal(metadata[:5], []byte{'m', 'e', 't', 'a', 15}) {
		t.Fatal("upstream fixture did not contain raw metadata15")
	}
	var vector struct {
		Call        string `json:"call_data_hex"`
		Extra       string `json:"included_in_extrinsic_hex"`
		Implicit    string `json:"included_in_signed_data_hex"`
		SpecVersion uint32 `json:"spec_version"`
		Proof       string `json:"rust_proof_hex"`
		JsProof     string `json:"polkadot_js_proof_hex"`
	}
	if err := json.Unmarshal(readPinned("sdk/bittensor-core/fixtures/ledger_proof_vector.json", "61b22baba06046ff8d3549921f8de7790b52e8587f0e088efea5c3e55699861f"), &vector); err != nil {
		t.Fatal(err)
	}
	decode := func(value string) []byte {
		raw, err := hex.DecodeString(value)
		if err != nil {
			t.Fatal(err)
		}
		return raw
	}
	helper, err := os.ReadFile("owner_ledger_adapter.py")
	if err != nil {
		t.Fatal(err)
	}
	directory := ownerSigningTestDirectory(t)
	helperPath := filepath.Join(directory, "owner_ledger_adapter.py")
	if err := os.WriteFile(helperPath, helper, 0600); err != nil {
		t.Fatal(err)
	}
	helperHash := sha256.Sum256(helper)
	config := ownerSigningDeviceConfig{StatePath: filepath.Join(directory, "device-state.json"), PythonPath: pythonPath,
		HelperPath: helperPath, HelperHash: "sha256:" + hex.EncodeToString(helperHash[:]),
		BackendPath: backendPath, BackendHash: backendHash, AppVersion: [3]uint16{100, 0, 5}}
	input := ownerSigningAdapterInput{Schema: ownerSigningAdapterSchema, Mode: "prepare", RequestHash: rootObjectHash("synthetic-native-sdk-fixture"),
		BackendPath: backendPath, BackendHash: backendHash, MetadataHex: "0x" + hex.EncodeToString(metadata),
		MetadataDigest: "0x8fae3c8fec8eb9487cbf8bfed255082223b82ec9f27de90d698a21443fa88f97",
		SpecName:       "node-subtensor", SpecVersion: vector.SpecVersion,
		Owner: "0x" + hex.EncodeToString(ownerSigningTestKey().Public().(ed25519.PublicKey)), Account: 7, Index: 3,
		Call: "0x" + vector.Call, IncludedExtrinsic: "0x" + vector.Extra, IncludedSignedData: "0x" + vector.Implicit,
		ResponsePath: config.StatePath + ".ledger-response", AppVersion: config.AppVersion}
	proof, jsProof := decode(vector.Proof), decode(vector.JsProof)
	if len(proof) < 512 || len(jsProof) < 512 {
		t.Fatal("upstream fixture lacks the independent proof envelope")
	}
	return ownerSigningNativeSdkFixture{config: config, input: input, proof: proof, jsTail: jsProof[len(jsProof)-512:]}
}

// Insert fixture code immediately before main. The native loader remains the
// production implementation; there is no production test flag or fallback.
func (self ownerSigningNativeSdkFixture) instrument(t *testing.T, source string) {
	t.Helper()
	helper, err := os.ReadFile("owner_ledger_adapter.py")
	if err != nil || bytes.Count(helper, []byte(`if __name__ == "__main__":`)) != 1 {
		t.Fatal("adapter main boundary changed", err)
	}
	helper = bytes.Replace(helper, []byte(`if __name__ == "__main__":`), []byte(source+"\n"+`if __name__ == "__main__":`), 1)
	if err := os.WriteFile(self.config.HelperPath, helper, 0600); err != nil {
		t.Fatal(err)
	}
}

// Read the exact native functions through the real loader and compare the full
// proof with Rust's source vector and its envelope with the independent JS one.
func TestOwnerSigningNativeSdkMatchesPinnedRfc78Vectors(t *testing.T) {
	fixture := newOwnerSigningNativeSdkFixture(t)
	fixture.instrument(t, `
request = json.load(sys.stdin)
backend = load_backend(request["backend_path"], request["backend_sha256"])
assert backend.__core_version__ == "0.1.0"
assert all(callable(getattr(backend.LedgerDevice, name)) for name in ("app_version", "address", "sign"))
chain = (bytes.fromhex(request["metadata_scale"][2:]), request["spec_version"], request["spec_name"], 42, 9, "TAO")
digest = bytes(backend.metadata_digest(*chain))
proof = bytes(backend.generate_extrinsic_proof(bytes.fromhex(request["call_scale"][2:]), bytes.fromhex(request["included_in_extrinsic"][2:]), bytes.fromhex(request["included_in_signed_data"][2:]), *chain))
print(json.dumps({"digest": "0x" + digest.hex(), "proof": proof.hex()}))
sys.exit(0)
`)
	raw, _ := json.Marshal(fixture.input)
	command := exec.CommandContext(t.Context(), fixture.config.PythonPath, "-I", fixture.config.HelperPath)
	command.Stdin = bytes.NewReader(raw)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatal("native loading or RFC78 vector failed", err, string(output))
	}
	var result struct {
		Digest string `json:"digest"`
		Proof  string `json:"proof"`
	}
	if err := json.Unmarshal(output, &result); err != nil || result.Digest != fixture.input.MetadataDigest || result.Proof != hex.EncodeToString(fixture.proof) ||
		!bytes.Equal(fixture.proof[len(fixture.proof)-512:], fixture.jsTail) {
		t.Fatal("native digest, complete proof or independent envelope changed", err)
	}
}

// Preparation executes the unmodified pinned helper through the Go command's
// subprocess seam. It emits no signature and creates no durable device reply.
func TestOwnerSigningNativeSdkPrepareUsesRealArtifact(t *testing.T) {
	fixture := newOwnerSigningNativeSdkFixture(t)
	result, err := runOwnerLedgerAdapter(t.Context(), fixture.config, fixture.input)
	proofHash := sha256.Sum256(fixture.proof)
	if err != nil || result.Schema != ownerSigningAdapterSchema || result.Mode != "prepare" || result.RequestHash != fixture.input.RequestHash ||
		result.SourceCommit != rootActionV1Source || result.MetadataDigest != fixture.input.MetadataDigest || result.ProofHash != "sha256:"+hex.EncodeToString(proofHash[:]) ||
		result.PublicKey != "" || result.Response != "" || result.AppVersion != [3]uint16{} {
		t.Fatalf("real native preparation differs: %+v %v", result, err)
	}
	if _, err := os.Stat(fixture.input.ResponsePath); !os.IsNotExist(err) {
		t.Fatal("preparation created a device response", err)
	}
}

// The upstream vector disables CheckMetadataHash. This separate native-codec
// case exercises the actual trim call with mortal era and enabled metadata
// hash, using synthetic chain hashes and no device or production account.
func TestOwnerSigningNativeSdkTrimMetadataHashEnabled(t *testing.T) {
	fixture := newOwnerSigningNativeSdkFixture(t)
	fixture.instrument(t, `
request = json.load(sys.stdin)
backend = load_backend(request["backend_path"], request["backend_sha256"])
metadata = bytes.fromhex(request["metadata_scale"][2:])
runtime = backend.Runtime(metadata, request["spec_version"], 1, 42)
call = bytes(runtime.compose_call("AdminUtils", "sudo_trim_to_max_allowed_uids", {"netuid": 25, "max_n": 6}))
digest = bytes.fromhex(request["metadata_digest"][2:])
extra, implicit = runtime.signature_payload_parts(era={"period": 8, "current": 64}, nonce=7, tip=0, tip_asset_id=None, genesis_hash=bytes([0x12])*32, era_block_hash=bytes([0x56])*32, metadata_hash=digest)
proof = bytes(backend.generate_extrinsic_proof(call, extra, implicit, metadata, request["spec_version"], request["spec_name"], 42, 9, "TAO"))
assert proof and len(call) + len(extra) + len(implicit) + len(proof) <= MAX_MESSAGE
print(json.dumps({"call": call.hex(), "extra": bytes(extra).hex(), "implicit": bytes(implicit).hex(), "proof_hash": "sha256:" + hashlib.sha256(proof).hexdigest()}))
sys.exit(0)
`)
	raw, _ := json.Marshal(fixture.input)
	command := exec.CommandContext(t.Context(), fixture.config.PythonPath, "-I", fixture.config.HelperPath)
	command.Stdin = bytes.NewReader(raw)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatal("native enabled-metadata trim fixture failed", err, string(output))
	}
	var parts struct {
		Call      string `json:"call"`
		Extra     string `json:"extra"`
		Implicit  string `json:"implicit"`
		ProofHash string `json:"proof_hash"`
	}
	if err := json.Unmarshal(output, &parts); err != nil {
		t.Fatal(err)
	}
	digest, _ := hex.DecodeString(fixture.input.MetadataDigest[2:])
	expectedImplicit := binary.LittleEndian.AppendUint32(nil, fixture.input.SpecVersion)
	expectedImplicit = binary.LittleEndian.AppendUint32(expectedImplicit, 1)
	expectedImplicit = append(expectedImplicit, bytes.Repeat([]byte{0x12}, 32)...)
	expectedImplicit = append(expectedImplicit, bytes.Repeat([]byte{0x56}, 32)...)
	expectedImplicit = append(expectedImplicit, 1)
	expectedImplicit = append(expectedImplicit, digest...)
	call, err := hex.DecodeString(parts.Call)
	if err != nil || len(call) != 6 || !bytes.Equal(call[2:], []byte{25, 0, 6, 0}) || parts.Extra != "02001c0001" ||
		parts.Implicit != hex.EncodeToString(expectedImplicit) || !planSha256(parts.ProofHash) {
		t.Fatal("native trim codec differs from the owner v2 payload grammar", err)
	}
	// Restore the unmodified helper before traversing the Go/Python adapter.
	helper, err := os.ReadFile("owner_ledger_adapter.py")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(fixture.config.HelperPath, helper, 0600); err != nil {
		t.Fatal(err)
	}
	fixture.input.Call, fixture.input.IncludedExtrinsic, fixture.input.IncludedSignedData = "0x"+parts.Call, "0x"+parts.Extra, "0x"+parts.Implicit
	result, err := runOwnerLedgerAdapter(t.Context(), fixture.config, fixture.input)
	if err != nil || result.ProofHash != parts.ProofHash || result.MetadataDigest != fixture.input.MetadataDigest || result.Mode != "prepare" {
		t.Fatal("owner adapter refused the native enabled-metadata trim proof", err)
	}
}

// The only substitute is LedgerDevice. A wrong key/version/proof must stop
// before the synthetic sign call, and success must retain exact response bytes.
func TestOwnerSigningNativeSdkDeviceBoundaryAndRefusals(t *testing.T) {
	for _, scenario := range []string{"valid", "wrong-key", "wrong-version", "wrong-digest", "changed-proof", "invalid-scheme", "short-signature", "existing-response"} {
		fixture := newOwnerSigningNativeSdkFixture(t)
		logPath := fixture.config.StatePath + ".calls"
		payload, err := hex.DecodeString(fixture.input.Call[2:] + fixture.input.IncludedExtrinsic[2:] + fixture.input.IncludedSignedData[2:])
		if err != nil || len(payload) > 256 {
			t.Fatal("upstream vector signing bytes changed", err)
		}
		signature := append([]byte{0}, ed25519.Sign(ownerSigningTestKey(), payload)...)
		params, _ := json.Marshal(map[string]any{"scenario": scenario, "log_path": logPath, "owner": fixture.input.Owner,
			"payload": hex.EncodeToString(payload), "proof": hex.EncodeToString(fixture.proof), "signature": hex.EncodeToString(signature)})
		fixture.instrument(t, fmt.Sprintf(`
fixture = json.loads(%q)
def fixture_log(value):
    with open(fixture["log_path"], "a", encoding="utf-8") as output:
        output.write(value + "\n")
class FixtureDevice:
    def __init__(self):
        fixture_log("open")
    def app_version(self):
        fixture_log("version")
        return (100, 0, 6) if fixture["scenario"] == "wrong-version" else (100, 0, 5)
    def address(self, account, index, prefix, confirm):
        assert (account, index, prefix, confirm) == (7, 3, 42, True)
        fixture_log("address")
        return (bytes(32) if fixture["scenario"] == "wrong-key" else bytes.fromhex(fixture["owner"][2:])), "synthetic-owner"
    def sign(self, payload, proof, account, index):
        assert payload.hex() == fixture["payload"] and proof.hex() == fixture["proof"]
        assert (account, index) == (7, 3)
        fixture_log("sign")
        signature = bytes.fromhex(fixture["signature"])
        if fixture["scenario"] == "invalid-scheme":
            return b"\x01" + signature[1:]
        if fixture["scenario"] == "short-signature":
            return signature[:-1]
        return signature
fixture_load_backend = load_backend
def load_backend(path, digest):
    backend = fixture_load_backend(path, digest)
    fixture_log("native-loaded")
    backend.LedgerDevice = FixtureDevice
    return backend
`, string(params)))
		helper, _ := os.ReadFile(fixture.config.HelperPath)
		helperHash := sha256.Sum256(helper)
		fixture.config.HelperHash = "sha256:" + hex.EncodeToString(helperHash[:])
		prepared, err := runOwnerLedgerAdapter(t.Context(), fixture.config, fixture.input)
		if err != nil {
			t.Fatal(scenario, "real native preparation failed", err)
		}
		before, _ := os.ReadFile(logPath)
		if string(before) != "native-loaded\n" {
			t.Fatal(scenario, "preparation touched the device", string(before))
		}
		fixture.input.Mode, fixture.input.ProofHash = "sign", prepared.ProofHash
		switch scenario {
		case "wrong-digest":
			fixture.input.MetadataDigest = "0x" + strings.Repeat("00", 32)
		case "changed-proof":
			fixture.input.ProofHash = "sha256:" + strings.Repeat("00", 32)
		case "existing-response":
			if err := os.WriteFile(fixture.input.ResponsePath, []byte("synthetic-original-response"), 0600); err != nil {
				t.Fatal(err)
			}
		}
		result, err := runOwnerLedgerAdapter(t.Context(), fixture.config, fixture.input)
		log, _ := os.ReadFile(logPath)
		expectedCalls := "native-loaded\nnative-loaded\n"
		switch scenario {
		case "valid", "invalid-scheme", "short-signature":
			expectedCalls += "open\nversion\naddress\nsign\n"
		case "wrong-key":
			expectedCalls += "open\nversion\naddress\n"
		case "wrong-version":
			expectedCalls += "open\nversion\n"
		}
		if string(log) != expectedCalls {
			t.Fatal(scenario, "device boundary differs", string(log))
		}
		response, readErr := os.ReadFile(fixture.input.ResponsePath)
		if scenario == "valid" {
			var retained ownerSigningAdapterResult
			if err != nil || readErr != nil || decodePlanJson(response, &retained) != nil || !reflect.DeepEqual(result, retained) || result.Response != "0x"+hex.EncodeToString(signature) ||
				result.PublicKey != fixture.input.Owner || result.AppVersion != fixture.config.AppVersion || result.ProofHash != prepared.ProofHash {
				t.Fatal("real native/device fixture did not retain the exact response", err, readErr)
			}
			info, _ := os.Stat(fixture.input.ResponsePath)
			if info.Mode().Perm() != 0600 {
				t.Fatal("device response is not private")
			}
			if _, err := runOwnerLedgerAdapter(t.Context(), fixture.config, fixture.input); err == nil {
				t.Fatal("existing durable response allowed another device call")
			}
			after, _ := os.ReadFile(logPath)
			if string(after) != expectedCalls+"native-loaded\n" {
				t.Fatal("repeated adapter call reached the device", string(after))
			}
		} else if err == nil {
			t.Fatal(scenario, "incompatible input or device was accepted")
		} else if scenario == "existing-response" {
			if readErr != nil || string(response) != "synthetic-original-response" {
				t.Fatal("original response was replaced", readErr)
			}
		} else if !os.IsNotExist(readErr) {
			t.Fatal(scenario, "refusal published a device response", readErr)
		}
	}
}

// These paths must fail before any unreviewed module can be executed. The
// success case above exercises the exact opened-inode loader on Linux.
func TestOwnerSigningNativeSdkRejectsArtifactSubstitution(t *testing.T) {
	for _, scenario := range []string{"wrong-hash", "symlink", "group-writable", "not-native"} {
		fixture := newOwnerSigningNativeSdkFixture(t)
		switch scenario {
		case "wrong-hash":
			fixture.input.BackendHash = "sha256:" + strings.Repeat("00", 32)
		case "symlink":
			path := fixture.config.StatePath + ".so"
			if err := os.Symlink(fixture.config.BackendPath, path); err != nil {
				t.Fatal(err)
			}
			fixture.input.BackendPath = path
		case "group-writable", "not-native":
			path := fixture.config.StatePath + ".so"
			raw := []byte("synthetic file; never executable native code")
			if scenario == "group-writable" {
				var err error
				raw, err = os.ReadFile(fixture.config.BackendPath)
				if err != nil {
					t.Fatal(err)
				}
			}
			if err := os.WriteFile(path, raw, 0600); err != nil {
				t.Fatal(err)
			}
			if scenario == "group-writable" {
				if err := os.Chmod(path, 0620); err != nil {
					t.Fatal(err)
				}
			}
			digest := sha256.Sum256(raw)
			fixture.input.BackendPath, fixture.input.BackendHash = path, "sha256:"+hex.EncodeToString(digest[:])
		}
		if _, err := runOwnerLedgerAdapter(t.Context(), fixture.config, fixture.input); err == nil {
			t.Fatal(scenario, "unreviewed native artifact was accepted")
		}
	}
}
