// Independently recorded pinned-SDK vectors exercise complete prefix coverage,
// including omitted branches whose point reads alone would appear sufficient.
package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"golang.org/x/crypto/blake2b"
)

// The SDK recorded raw reads and separately generated incompatible trie proofs.
type safeCurrentStorageOracleCase struct {
	Name    string `json:"name"`
	Layout  string `json:"layout"`
	Root    string `json:"root"`
	Entries []struct {
		Key   string  `json:"key"`
		Value *string `json:"value"`
	} `json:"entries"`
	Reads []struct {
		Key   string  `json:"key"`
		Value *string `json:"value"`
	} `json:"reads"`
	Nodes     []string `json:"storage_proof_nodes"`
	Generated []string `json:"generated_trie_proof_nodes"`
}

// This unchanged fixture was generated by the pinned SDK's recorder, not by
// either Go trie decoder or the Safe fixture's independent mutation encoder.
func safeCurrentStorageOracle(t *testing.T) []safeCurrentStorageOracleCase {
	t.Helper()
	raw, err := os.ReadFile("testdata/safe-current-storage-sdk-oracle.json")
	if err != nil {
		t.Fatal(err)
	}
	digest := sha256.Sum256(raw)
	if hex.EncodeToString(digest[:]) != "b875b9eb1aa497233f68bb4cae02b4331320fcaeeaaefbefe867658f2aebaecd" {
		t.Fatal("independent native SDK oracle bytes changed")
	}
	var oracle struct {
		Schema string                         `json:"schema"`
		Sdk    string                         `json:"sdk_source"`
		Cases  []safeCurrentStorageOracleCase `json:"cases"`
	}
	if err := decodePlanJson(raw, &oracle); err != nil || oracle.Schema != "urnetwork-native-storage-sdk-oracle-v1" || oracle.Sdk != safeCurrentStorageSdk || len(oracle.Cases) != 18 {
		t.Fatal("independent native SDK oracle scope differs", err)
	}
	return oracle.Cases
}

// Both layouts cover empty/branch/odd/long/inline/external-value forms and prove
// absence without equating an omitted node or present empty value with absence.
func TestSafeCurrentStoragePrefixMatchesPinnedSdk(t *testing.T) {
	for _, vector := range safeCurrentStorageOracle(t) {
		trie, err := newSafeCurrentStorageTrie(t.Context(), vector.Nodes)
		if err != nil {
			t.Fatal(vector.Name, err)
		}
		root := [32]byte(common.HexToHash(vector.Root))
		for _, read := range vector.Reads {
			value, present, err := trie.read(t.Context(), root, common.FromHex(read.Key))
			if err != nil || present != (read.Value != nil) || present && !bytes.Equal(value, common.FromHex(*read.Value)) {
				t.Fatal("native point read differs from SDK", vector.Name, read.Key, err)
			}
		}
		prefix := []byte{}
		if strings.HasSuffix(vector.Name, "partial-proof") {
			prefix = []byte{0x10}
		}
		values, err := trie.prefix(t.Context(), root, prefix)
		if err != nil {
			t.Fatal("complete matching prefix was refused", vector.Name, err)
		}
		count := 0
		for _, entry := range vector.Entries {
			key := common.FromHex(entry.Key)
			if !bytes.HasPrefix(key, prefix) {
				continue
			}
			count++
			value, present := values[string(key)]
			if !present || entry.Value == nil || !bytes.Equal(value, common.FromHex(*entry.Value)) {
				t.Fatal("complete native prefix lost an SDK entry", vector.Name, entry.Key)
			}
		}
		if count != len(values) {
			t.Fatal("complete prefix invented extra entries", vector.Name)
		}
	}
}

// A union of successful requested reads is insufficient when an intersecting
// hash remains unresolved. Siblings outside the selected prefix are irrelevant.
func TestSafeCurrentStoragePrefixRejectsOmittedCoverage(t *testing.T) {
	for _, vector := range safeCurrentStorageOracle(t) {
		if !strings.HasSuffix(vector.Name, "partial-proof") {
			continue
		}
		trie, err := newSafeCurrentStorageTrie(t.Context(), vector.Nodes)
		if err != nil {
			t.Fatal(err)
		}
		root := [32]byte(common.HexToHash(vector.Root))
		if values, err := trie.prefix(t.Context(), root, []byte{0x10}); err != nil || len(values) != 1 {
			t.Fatal("unrelated missing branch blocked exact prefix", err)
		}
		for _, prefix := range [][]byte{nil, {0x20}, {0x30}} {
			if values, err := trie.prefix(t.Context(), root, prefix); err == nil || values != nil || !strings.Contains(err.Error(), "missing node") {
				t.Fatal("complete-prefix proof accepted an omitted intersecting branch", vector.Name, err)
			}
		}
		generated, err := newSafeCurrentStorageTrie(t.Context(), vector.Generated)
		if err == nil {
			_, err = generated.prefix(t.Context(), root, []byte{0x10})
		}
		if err == nil {
			t.Fatal("generated proof encoding replaced raw StorageProof", vector.Name)
		}
	}
}

// Header root substitution, missing external values, duplicate blobs, malformed
// nodes and cancellation return no partial successful census.
func TestSafeCurrentStoragePrefixRejectsMalformedProofs(t *testing.T) {
	for _, vector := range safeCurrentStorageOracle(t) {
		if vector.Name != "layout1-hashed-branch-value" {
			continue
		}
		root := [32]byte(common.HexToHash(vector.Root))
		trie, err := newSafeCurrentStorageTrie(t.Context(), vector.Nodes)
		if err != nil {
			t.Fatal(err)
		}
		changedRoot := root
		changedRoot[0] ^= 1
		if values, err := trie.prefix(t.Context(), changedRoot, nil); err == nil || values != nil {
			t.Fatal("native proof accepted a substituted state root")
		}
		removed := 0
		nodes := slices.DeleteFunc(slices.Clone(vector.Nodes), func(node string) bool {
			if node == *vector.Entries[0].Value {
				removed++
				return true
			}
			return false
		})
		if removed != 1 {
			t.Fatal("missing external value fixture did not remove one blob")
		}
		trie, err = newSafeCurrentStorageTrie(t.Context(), nodes)
		if err != nil {
			t.Fatal(err)
		}
		if values, err := trie.prefix(t.Context(), root, nil); err == nil || values != nil || !strings.Contains(err.Error(), "missing external value") {
			t.Fatal("complete prefix accepted an omitted external value", err)
		}
		if _, err := newSafeCurrentStorageTrie(t.Context(), append(slices.Clone(vector.Nodes), vector.Nodes[0])); err == nil {
			t.Fatal("native proof accepted duplicate blobs")
		}
	}
	for _, raw := range [][]byte{{0, 0}, {0x41, 0xf1, 0}, {0x80, 0, 0}, {0x41}, {0x41, 1, 5, 0}, {0x01}} {
		trie, err := newSafeCurrentStorageTrie(t.Context(), []string{"0x" + hex.EncodeToString(raw)})
		if err != nil {
			t.Fatal(err)
		}
		if values, err := trie.prefix(t.Context(), blake2b.Sum256(raw), nil); err == nil || values != nil {
			t.Fatal("native proof accepted a malformed canonical node", raw)
		}
	}
	for _, nodes := range [][]string{{"0X00"}, {"0xAA"}, {"0x0"}, make([]string, maximumSafeCurrentProofNodes+1), {"0x" + strings.Repeat("00", maximumSafeCurrentProofItemBytes+1)}} {
		if _, err := newSafeCurrentStorageTrie(t.Context(), nodes); err == nil {
			t.Fatal("native proof accepted malformed or unbounded input")
		}
	}
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	trie, err := newSafeCurrentStorageTrie(t.Context(), nil)
	if err != nil {
		t.Fatal(err)
	}
	if values, err := trie.prefix(ctx, blake2b.Sum256([]byte{0}), nil); !errors.Is(err, context.Canceled) || values != nil {
		t.Fatal("canceled native proof produced a census", err)
	}
}
