//go:build linux || darwin

// Actual native and Evm transports feed the production activation producer.
// Tiny explicitly pinned metadata is fixture authority, not a live deployment
// claim; no callback can approve stake, identity or a prepared activation.
package main

import (
	"bytes"
	"context"
	"crypto/ed25519"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"sync"
	"testing"

	gsrpc "github.com/centrifuge/go-substrate-rpc-client/v4"
	gsrpcgeth "github.com/centrifuge/go-substrate-rpc-client/v4/gethrpc"
	"github.com/centrifuge/go-substrate-rpc-client/v4/types"
	"github.com/centrifuge/go-substrate-rpc-client/v4/types/codec"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/urfoundation/sn/crv4"
	"github.com/urfoundation/sn/stabi"
	validatorcomponent "github.com/urfoundation/sn/validator"
)

// The production Gsrpc client owns cancellation and response decoding. The
// only adaptation is the endpoint method required by its public interface.
type runtimeEvidenceNativeRpcClientV2 struct {
	*gsrpcgeth.Client
	endpoint string
}

func (self *runtimeEvidenceNativeRpcClientV2) URL() string { return self.endpoint }

type runtimeEvidenceNativeKeyV2 struct {
	name   string
	hotkey [32]byte
	uid    uint16
}

// Test mutations are serialized with individual raw responses; tests alter
// state only after the previous complete production call has returned.
type runtimeEvidenceActivationRpcV2TestFixture struct {
	base               *runtimeEvidenceProvisionV2TestFixture
	executor           *Executor
	chain              *validatorcomponent.ChainClient
	stateLock          sync.Mutex
	metadataHex        string
	nativeRuntime      crv4.RuntimeArtifactIdentity
	nativeHash         types.Hash
	nativeNumber       uint64
	genesis            types.Hash
	evmHash            common.Hash
	evmNumber          uint64
	finalizedEvmNumber uint64
	finalizedEvmHash   common.Hash
	hotkeys            [3][32]byte
	permits            [3]bool
	totalStake         [3]uint64
	threshold          uint64
	storageKeys        map[string]runtimeEvidenceNativeKeyV2
	views              map[string]string
	calls              map[string]uint64
}

// Both validators inhabit one real three-entry census. Storage keys use the
// reviewed identity/Blake2 hashers and are generated by the independent SDK.
func newRuntimeEvidenceActivationRpcV2TestFixture(t *testing.T) *runtimeEvidenceActivationRpcV2TestFixture {
	t.Helper()
	base := newRuntimeEvidenceProvisionV2TestFixture(t)
	stateDir, err := filepath.EvalSymlinks(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(stateDir, 0o700); err != nil {
		t.Fatal(err)
	}
	self := &runtimeEvidenceActivationRpcV2TestFixture{base: base, nativeHash: types.Hash{0x31}, nativeNumber: 100, genesis: types.Hash(base.plan.ValidatorEvidence.GenesisHash),
		evmHash: common.Hash{0x32}, evmNumber: 200, finalizedEvmNumber: 200, finalizedEvmHash: common.Hash{0x32}, threshold: 100,
		hotkeys: [3][32]byte{{0x71}}, permits: [3]bool{false, true, true}, totalStake: [3]uint64{0, 150, 170}, storageKeys: map[string]runtimeEvidenceNativeKeyV2{}, views: map[string]string{}, calls: map[string]uint64{}}
	if base.cfg.Config.Topology.Validators != 2 || base.cfg.Config.Topology.Operators != 2 {
		t.Fatal("activation transport fixture requires the real four source pairs")
	}
	for validatorId := 1; validatorId <= 2; validatorId++ {
		key, _, err := runtimeEvidenceActivationKeysV2(base.roles, uint64(validatorId), 1)
		if err != nil {
			t.Fatal(err)
		}
		self.hotkeys[validatorId] = key.PublicKey()
	}
	identity := types.StorageHasherV10{IsIdentity: true}
	account := types.StorageHasherV10{IsBlake2_128Concat: true}
	metadata := types.NewMetadataV14()
	metadata.MagicNumber = types.MagicNumber
	metadata.AsMetadataV14.Pallets = []types.PalletMetadataV14{{Name: "SubtensorModule", HasStorage: true, Storage: types.StorageMetadataV14{Prefix: "SubtensorModule"}}}
	for _, field := range []struct {
		name     string
		optional bool
		hashers  []types.StorageHasherV10
	}{
		{name: "SubnetworkN", hashers: []types.StorageHasherV10{identity}}, {name: "Keys", hashers: []types.StorageHasherV10{identity, identity}},
		{name: "Uids", optional: true, hashers: []types.StorageHasherV10{identity, account}}, {name: "Owner", hashers: []types.StorageHasherV10{account}},
		{name: "TotalHotkeyAlpha", hashers: []types.StorageHasherV10{account, identity}}, {name: "ValidatorPermit", hashers: []types.StorageHasherV10{identity}},
		{name: "SubnetOwnerHotkey", hashers: []types.StorageHasherV10{identity}}, {name: "StakeThreshold"}, {name: "SubnetEpochIndex", hashers: []types.StorageHasherV10{identity}},
	} {
		entry := types.StorageEntryMetadataV14{Name: types.Text(field.name), Modifier: types.StorageFunctionModifierV0{IsOptional: field.optional, IsDefault: !field.optional}}
		if len(field.hashers) == 0 {
			entry.Type = types.StorageEntryTypeV14{IsPlainType: true}
		} else {
			entry.Type = types.StorageEntryTypeV14{IsMap: true, AsMap: types.MapTypeV14{Hashers: field.hashers}}
		}
		metadata.AsMetadataV14.Pallets[0].Storage.Items = append(metadata.AsMetadataV14.Pallets[0].Storage.Items, entry)
	}
	self.metadataHex, err = codec.EncodeToHex(metadata)
	if err != nil {
		t.Fatal(err)
	}
	_, metadataHash, err := crv4.DecodeRuntimeMetadata(self.metadataHex)
	if err != nil {
		t.Fatal(err)
	}
	self.nativeRuntime = crv4.RuntimeArtifactIdentity{Version: crv4.RuntimeVersionIdentity{SpecName: "node-subtensor", SpecVersion: 454, TransactionVersion: 1, StateVersion: 1}, CodeHash: types.Hash{4}.Hex(), MetadataHash: metadataHash}
	// These test-only pins are fixed before transport starts. The production
	// reader must obtain the exact corresponding bytes through the native Rpc.
	base.cfg.Release.Runtime.CodeHash, base.cfg.Release.Runtime.MetadataHash = self.nativeRuntime.CodeHash, metadataHash
	base.cfg.Public.Chain.ExpectedRuntimeSpec, base.cfg.Public.Chain.ExpectedTransactionVersion, base.cfg.Public.Chain.ExpectedStateVersion = 454, 1, 1
	netuid := binary.LittleEndian.AppendUint16(nil, base.cfg.Netuid)
	add := func(value runtimeEvidenceNativeKeyV2, args ...[]byte) {
		key, err := types.CreateStorageKey(metadata, "SubtensorModule", value.name, args...)
		if err != nil {
			t.Fatal(err)
		}
		if _, exists := self.storageKeys[key.Hex()]; exists {
			t.Fatal("native activation fixture storage keys collide")
		}
		self.storageKeys[key.Hex()] = value
	}
	for _, name := range []string{"SubnetworkN", "ValidatorPermit", "SubnetOwnerHotkey", "SubnetEpochIndex"} {
		add(runtimeEvidenceNativeKeyV2{name: name}, netuid)
	}
	add(runtimeEvidenceNativeKeyV2{name: "StakeThreshold"})
	for uid, hotkey := range self.hotkeys {
		add(runtimeEvidenceNativeKeyV2{name: "Keys", uid: uint16(uid)}, netuid, binary.LittleEndian.AppendUint16(nil, uint16(uid)))
		add(runtimeEvidenceNativeKeyV2{name: "Uids", hotkey: hotkey}, netuid, hotkey[:])
		add(runtimeEvidenceNativeKeyV2{name: "Owner", hotkey: hotkey}, hotkey[:])
		add(runtimeEvidenceNativeKeyV2{name: "TotalHotkeyAlpha", hotkey: hotkey}, hotkey[:], netuid)
	}
	coordinator := stabi.NewSTCoordinator()
	parsed, err := stabi.STCoordinatorMetaData.ParseABI()
	if err != nil {
		t.Fatal(err)
	}
	policyHash, err := decodeHex32("activation transport policy", base.cfg.PolicyHash)
	if err != nil {
		t.Fatal(err)
	}
	addView := func(data []byte, method string, value any) {
		encoded, err := parsed.Methods[method].Outputs.Pack(value)
		if err != nil {
			t.Fatal(err)
		}
		self.views[hexutil.Encode(data)] = hexutil.Encode(encoded)
	}
	addView(coordinator.PackCurrentEpoch(), "currentEpoch", big.NewInt(8))
	addView(coordinator.PackPolicyAt(big.NewInt(9)), "policyAt", stabi.STCoordinatorPolicySnapshot{PolicyHash: policyHash, EffectiveEpoch: 9, EffectiveBlock: 210, EpochBlocks: 100, EpochDepositCapRao: big.NewInt(1000), CampaignDepositCapRao: big.NewInt(5000)})
	for noId := int64(1); noId <= 2; noId++ {
		addView(coordinator.PackOperatorAt(big.NewInt(noId), big.NewInt(9)), "operatorAt", stabi.STCoordinatorOperatorVersion{Active: true, EffectiveEpoch: 9})
	}
	server := httptest.NewServer(http.HandlerFunc(self.serve))
	t.Cleanup(server.Close)
	nativeClient, err := gsrpcgeth.DialContext(t.Context(), server.URL)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(nativeClient.Close)
	native := &crv4.Chain{API: &gsrpc.SubstrateAPI{Client: &runtimeEvidenceNativeRpcClientV2{Client: nativeClient, endpoint: server.URL}}, GenesisHash: self.genesis, Meta: types.NewMetadataV14(), Runtime: &types.RuntimeVersion{SpecName: "unrelated-dial-time"}}
	evmClient, err := ethclient.DialContext(t.Context(), server.URL)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(evmClient.Close)
	self.chain, err = validatorcomponent.DialReleaseChainContext(t.Context(), []string{server.URL}, base.plan.ValidatorEvidence.Coordinator)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(self.chain.Close)
	self.executor = &Executor{cfg: base.cfg, roles: base.roles, plan: base.plan, stateDir: stateDir, substrate: &SubstrateManager{chain: native}, keeper: &EvmTxManager{client: evmClient}}
	return self
}

// The byte-limited real Http server reports unexpected methods/arguments as
// transport errors. It never returns an eligibility or activation verdict.
func (self *runtimeEvidenceActivationRpcV2TestFixture) serve(writer http.ResponseWriter, request *http.Request) {
	var call struct {
		Jsonrpc string            `json:"jsonrpc"`
		Id      json.RawMessage   `json:"id"`
		Method  string            `json:"method"`
		Params  []json.RawMessage `json:"params"`
	}
	if err := json.NewDecoder(io.LimitReader(request.Body, 32*1024)).Decode(&call); err != nil {
		writer.WriteHeader(http.StatusBadRequest)
		return
	}
	result, err := func() (any, error) {
		self.stateLock.Lock()
		defer self.stateLock.Unlock()
		self.calls[call.Method]++
		return self.dispatchWithLock(request.Context(), call.Method, call.Params)
	}()
	response := map[string]any{"jsonrpc": "2.0", "id": call.Id}
	if err == nil {
		response["result"] = result
	} else {
		response["error"] = map[string]any{"code": -32000, "message": err.Error()}
	}
	writer.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(writer).Encode(response)
}

// Each storage read is exact-block. Reverse and forward registration, permit
// and calculated metagraph stake share the same independently served census.
func (self *runtimeEvidenceActivationRpcV2TestFixture) dispatchWithLock(ctx context.Context, method string, params []json.RawMessage) (any, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	check := func(want ...any) error {
		if len(params) != len(want) {
			return fmt.Errorf("activation %s parameter count differs", method)
		}
		for index, expected := range want {
			raw, err := json.Marshal(expected)
			if err != nil || !bytes.Equal(raw, params[index]) {
				return fmt.Errorf("activation %s parameter %d differs", method, index)
			}
		}
		return nil
	}
	hexBytes := func(value []byte) string { return "0x" + hex.EncodeToString(value) }
	switch method {
	case "eth_chainId":
		if err := check(); err != nil {
			return nil, err
		}
		return hexutil.EncodeUint64(testnetChainID), nil
	case "eth_getBlockByNumber":
		if len(params) != 2 {
			return nil, errors.New("activation Evm block parameter count differs")
		}
		var selector string
		if err := json.Unmarshal(params[0], &selector); err != nil {
			return nil, err
		}
		if err := check(selector, false); err != nil {
			return nil, err
		}
		if selector == "finalized" {
			return map[string]any{"number": hexutil.EncodeUint64(self.finalizedEvmNumber), "hash": self.finalizedEvmHash}, nil
		}
		if selector == hexutil.EncodeUint64(self.evmNumber) {
			return map[string]any{"number": selector, "hash": self.evmHash}, nil
		}
		return nil, errors.New("activation Evm block selector is not independently known")
	case "eth_call":
		if len(params) != 2 || string(params[1]) != fmt.Sprintf("%q", hexutil.EncodeUint64(self.evmNumber)) {
			return nil, errors.New("activation coordinator call lost its historical block")
		}
		var call struct {
			To    common.Address `json:"to"`
			Input hexutil.Bytes  `json:"input"`
			Data  hexutil.Bytes  `json:"data"`
		}
		if err := json.Unmarshal(params[0], &call); err != nil {
			return nil, err
		}
		if call.To != self.base.plan.ValidatorEvidence.Coordinator {
			return nil, errors.New("activation coordinator target differs")
		}
		data := call.Input
		if len(data) == 0 {
			data = call.Data
		}
		value, found := self.views[hexutil.Encode(data)]
		if !found {
			return nil, errors.New("activation coordinator calldata is not independently known")
		}
		return value, nil
	case "chain_getFinalizedHead":
		if err := check(); err != nil {
			return nil, err
		}
		return self.nativeHash.Hex(), nil
	case "chain_getHeader":
		if err := check(self.nativeHash.Hex()); err != nil {
			return nil, err
		}
		return map[string]any{"parentHash": types.Hash{}.Hex(), "number": hexutil.EncodeUint64(self.nativeNumber), "stateRoot": types.Hash{5}.Hex(), "extrinsicsRoot": types.Hash{6}.Hex(), "digest": map[string]any{"logs": []string{}}}, nil
	case "chain_getBlockHash":
		if len(params) != 1 {
			return nil, errors.New("activation native block parameter count differs")
		}
		var number uint64
		if err := json.Unmarshal(params[0], &number); err != nil {
			return nil, err
		}
		if number == 0 {
			return self.genesis.Hex(), nil
		}
		if number == self.nativeNumber {
			return self.nativeHash.Hex(), nil
		}
		return nil, errors.New("activation native block is not independently known")
	case "state_getRuntimeVersion":
		if err := check(self.nativeHash.Hex()); err != nil {
			return nil, err
		}
		return self.nativeRuntime.Version, nil
	case "state_getStorageHash":
		if err := check("0x3a636f6465", self.nativeHash.Hex()); err != nil {
			return nil, err
		}
		return self.nativeRuntime.CodeHash, nil
	case "state_getMetadata":
		if err := check(self.nativeHash.Hex()); err != nil {
			return nil, err
		}
		return self.metadataHex, nil
	case "state_getStorage":
		if len(params) != 2 {
			return nil, errors.New("activation native storage parameter count differs")
		}
		var key string
		if err := json.Unmarshal(params[0], &key); err != nil {
			return nil, err
		}
		if err := check(key, self.nativeHash.Hex()); err != nil {
			return nil, err
		}
		field, found := self.storageKeys[key]
		if !found {
			return nil, errors.New("activation native storage key is not in pinned metadata")
		}
		switch field.name {
		case "SubnetworkN":
			return hexBytes([]byte{3, 0}), nil
		case "Keys":
			return hexBytes(self.hotkeys[field.uid][:]), nil
		case "Uids":
			for uid, hotkey := range self.hotkeys {
				if hotkey == field.hotkey {
					return hexBytes(binary.LittleEndian.AppendUint16(nil, uint16(uid))), nil
				}
			}
			return nil, nil
		case "Owner":
			return hexBytes(bytes.Repeat([]byte{0x72}, 32)), nil
		case "TotalHotkeyAlpha":
			return hexBytes(binary.LittleEndian.AppendUint64(nil, 9_000_000_000_000_000)), nil
		case "ValidatorPermit":
			value := []byte{12}
			for _, permit := range self.permits {
				if permit {
					value = append(value, 1)
				} else {
					value = append(value, 0)
				}
			}
			return hexBytes(value), nil
		case "SubnetOwnerHotkey":
			return nil, nil
		case "StakeThreshold":
			return hexBytes(binary.LittleEndian.AppendUint64(nil, self.threshold)), nil
		case "SubnetEpochIndex":
			return hexBytes(binary.LittleEndian.AppendUint64(nil, 77)), nil
		}
	case "state_call":
		payload := binary.LittleEndian.AppendUint16(nil, self.base.cfg.Netuid)
		payload = append(payload, 20, 0, 0, 30, 0, 52, 0, 57, 0, 69, 0)
		if err := check("SubnetInfoRuntimeApi_get_selective_metagraph", hexBytes(payload), self.nativeHash.Hex()); err != nil {
			return nil, err
		}
		data := []byte{1}
		compact := func(value uint64) error {
			encoded, err := codec.Encode(types.NewUCompactFromUInt(value))
			if err == nil {
				data = append(data, encoded...)
			}
			return err
		}
		if err := compact(uint64(self.base.cfg.Netuid)); err != nil {
			return nil, err
		}
		for field := 1; field <= 76; field++ {
			if field != 30 && field != 52 && field != 57 && field != 69 {
				data = append(data, 0)
				continue
			}
			data = append(data, 1)
			if err := compact(3); err != nil {
				return nil, err
			}
			switch field {
			case 52:
				for _, hotkey := range self.hotkeys {
					data = append(data, hotkey[:]...)
				}
			case 57:
				for _, permit := range self.permits {
					if permit {
						data = append(data, 1)
					} else {
						data = append(data, 0)
					}
				}
			case 69:
				for _, total := range self.totalStake {
					if err := compact(total); err != nil {
						return nil, err
					}
				}
			}
		}
		return hexBytes(data), nil
	}
	return nil, fmt.Errorf("unexpected activation transport method %s", method)
}

// Snapshot counters only after a complete production operation has joined.
func (self *runtimeEvidenceActivationRpcV2TestFixture) callCount(method string) uint64 {
	self.stateLock.Lock()
	defer self.stateLock.Unlock()
	return self.calls[method]
}

func TestRuntimeEvidenceActivationRpcV2PreparesFourActualSignedSources(t *testing.T) {
	fixture := newRuntimeEvidenceActivationRpcV2TestFixture(t)
	prepared, encoded, err := fixture.executor.prepareRuntimeEvidenceActivationsV2(t.Context(), fixture.chain)
	if err != nil {
		t.Fatal(err)
	}
	if prepared.Epoch != 9 || prepared.Native.Number != 100 || prepared.Native.Hash != fixture.nativeHash.Hex() || prepared.Evm.Number != 200 || prepared.Evm.Hash != fixture.evmHash.Hex() || len(prepared.Members) != 4 {
		t.Fatalf("actual prepared snapshots or source census differ: %+v", prepared)
	}
	for index, member := range prepared.Members {
		validatorId, noId := uint64(index/2+1), uint64(index%2+1)
		hotkey, key, err := runtimeEvidenceActivationKeysV2(fixture.base.roles, validatorId, noId)
		if err != nil {
			t.Fatal(err)
		}
		if member.ValidatorId != validatorId || member.NoId != noId || member.ValidatorUid != uint16(validatorId) || member.Activation.Hotkey != hotkey.PublicKey() || member.Activation.VPK != [32]byte(key[ed25519.SeedSize:]) {
			t.Fatal("producer substituted a role, uid or source key")
		}
		if err := member.Activation.Verify(member.Activation, member.VpkSignature, member.HotkeySignature); err != nil {
			t.Fatal(err)
		}
	}
	if fixture.callCount("state_call") != 8 || fixture.callCount("state_getMetadata") == 0 || fixture.callCount("state_getStorage") == 0 {
		t.Fatal("preparation bypassed actual metadata, registration, permit or calculated stake")
	}
	actual, err := os.ReadFile(filepath.Join(fixture.executor.stateDir, "evidence-v2-setup", "prepared.json"))
	if err != nil || !bytes.Equal(actual, encoded) {
		t.Fatalf("original signed preparation was not retained: %v", err)
	}
}

func TestRuntimeEvidenceActivationRpcV2RetryRetainsOriginalSignedBytes(t *testing.T) {
	fixture := newRuntimeEvidenceActivationRpcV2TestFixture(t)
	first, encoded, err := fixture.executor.prepareRuntimeEvidenceActivationsV2(t.Context(), fixture.chain)
	if err != nil {
		t.Fatal(err)
	}
	func() {
		fixture.stateLock.Lock()
		defer fixture.stateLock.Unlock()
		fixture.finalizedEvmNumber, fixture.finalizedEvmHash = 201, common.Hash{0x33}
	}()
	before := fixture.callCount("state_call")
	again, repeated, err := fixture.executor.prepareRuntimeEvidenceActivationsV2(t.Context(), fixture.chain)
	if err != nil || !bytes.Equal(repeated, encoded) || !reflect.DeepEqual(again, first) {
		t.Fatalf("retry replaced historical snapshots or randomized consents: %v", err)
	}
	if fixture.callCount("state_call") != before+4 {
		t.Fatal("retry skipped actual historical source eligibility")
	}
}

func TestRuntimeEvidenceActivationRpcV2RejectsChangedHistoricalUid(t *testing.T) {
	fixture := newRuntimeEvidenceActivationRpcV2TestFixture(t)
	_, encoded, err := fixture.executor.prepareRuntimeEvidenceActivationsV2(t.Context(), fixture.chain)
	if err != nil {
		t.Fatal(err)
	}
	func() {
		fixture.stateLock.Lock()
		defer fixture.stateLock.Unlock()
		fixture.hotkeys[1], fixture.hotkeys[2] = fixture.hotkeys[2], fixture.hotkeys[1]
	}()
	before := fixture.callCount("state_call")
	prepared, repeated, err := fixture.executor.prepareRuntimeEvidenceActivationsV2(t.Context(), fixture.chain)
	if err == nil || prepared != nil || repeated != nil || fixture.callCount("state_call") <= before {
		t.Fatalf("changed actual historical uid was accepted or skipped: %v", err)
	}
	actual, readErr := os.ReadFile(filepath.Join(fixture.executor.stateDir, "evidence-v2-setup", "prepared.json"))
	if readErr != nil || !bytes.Equal(actual, encoded) {
		t.Fatalf("rejected history replaced retained consents: %v", readErr)
	}
}

func TestRuntimeEvidenceActivationRpcV2RejectsLostHistoricalPermit(t *testing.T) {
	fixture := newRuntimeEvidenceActivationRpcV2TestFixture(t)
	prepared, encoded, err := fixture.executor.prepareRuntimeEvidenceActivationsV2(t.Context(), fixture.chain)
	if err != nil {
		t.Fatal(err)
	}
	func() { fixture.stateLock.Lock(); defer fixture.stateLock.Unlock(); fixture.permits[1] = false }()
	before := fixture.callCount("state_call")
	if err := fixture.executor.authenticateRuntimeEvidencePreparedV2(t.Context(), fixture.chain, prepared); err == nil || fixture.callCount("state_call") <= before {
		t.Fatalf("lost permit became an eligible historical source: %v", err)
	}
	actual, err := os.ReadFile(filepath.Join(fixture.executor.stateDir, "evidence-v2-setup", "prepared.json"))
	if err != nil || !bytes.Equal(actual, encoded) {
		t.Fatalf("failed historical eligibility changed signed bytes: %v", err)
	}
}

func TestRuntimeEvidenceActivationRpcV2RejectsRawAlphaWithoutCalculatedStake(t *testing.T) {
	fixture := newRuntimeEvidenceActivationRpcV2TestFixture(t)
	func() { fixture.stateLock.Lock(); defer fixture.stateLock.Unlock(); fixture.totalStake[1] = 99 }()
	prepared, encoded, err := fixture.executor.prepareRuntimeEvidenceActivationsV2(t.Context(), fixture.chain)
	if err == nil || prepared != nil || encoded != nil || fixture.callCount("state_call") == 0 {
		t.Fatalf("large raw alpha replaced insufficient real calculated stake: %v", err)
	}
	if _, err := os.Lstat(filepath.Join(fixture.executor.stateDir, "evidence-v2-setup", "prepared.json")); !errors.Is(err, os.ErrNotExist) {
		t.Fatal("ineligible source published a signed preparation")
	}
}
