//go:build linux || darwin

// The actual cache refresh uses real chain/metadata readers; only the clock
// and exact RPC state transitions are independently controlled by the test.
package validator

import (
	"context"
	"crypto/ed25519"
	"crypto/sha256"
	"errors"
	"testing"
	"time"

	"github.com/urfoundation/sn/v2026/protocol"
)

// No management loop is started by this private-state fixture. Tests call the
// actual refresh synchronously and explicitly join every lease on cleanup.
func validatorUploadAdmissionTestState(t *testing.T, fixture *validatorUploadAuthorityTestFixture) *ValidatorUploadAdmission {
	t.Helper()
	owner, err := newValidatorUploadAdmissionState(t.Context(), fixture.chain, fixture.native.chain, fixture.config())
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { owner.cancel(); owner.invalidate(errors.New("fixture closed")); owner.leases.Wait() })
	if err := owner.refresh(t.Context(), fixture.now); err != nil {
		t.Fatalf("real complete activation/current-permit cache prerequisite: %v", err)
	}
	return owner
}

// Consent is generated by the source activation's real private key while the
// destination's current account token is independently supplied to Begin.
func validatorUploadAdmissionTestHeader(t *testing.T, fixture *validatorUploadAuthorityTestFixture, record protocol.ValidatorEvidenceActivation, seed byte, credential string, data []byte) (string, [32]byte, [32]byte) {
	t.Helper()
	privateKey := ed25519.NewKeyFromSeed(append([]byte{seed}, make([]byte, 31)...))
	signer, err := newValidatorAttemptUploadSigner(record, fixture.config().ReplicaNoID, fixture.config().MaximumIntentSeconds, privateKey)
	if err != nil {
		t.Fatal(err)
	}
	digest := sha256.Sum256(data)
	header, err := signer.headerAt(credential, "metadata", digest, uint64(len(data)), fixture.now)
	if err != nil {
		t.Fatal(err)
	}
	sessionHash, err := protocol.ValidatorAttemptUploadSessionHash(credential)
	if err != nil {
		t.Fatal(err)
	}
	return header, sessionHash, digest
}

// No startup list is required for a later external validator. Current native
// UID remains a chain observation, while the quota owner is the stable hotkey.
func TestValidatorUploadAdmissionDiscoversExternalOwnerWithoutReferenceList(t *testing.T) {
	t.Parallel()
	fixture := newValidatorUploadAuthorityTestFixture(t)
	owner := validatorUploadAdmissionTestState(t, fixture)
	header, sessionHash, digest := validatorUploadAdmissionTestHeader(t, fixture, fixture.authority.Expected, 0x41, "current-api-client", []byte("object"))
	lease, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now)
	if err != nil {
		t.Fatalf("external eligible validator was limited to startup references: %v", err)
	}
	defer lease.Close()
	if lease.Owner() != (ValidatorUploadOwner{Hotkey: fixture.authority.Expected.Hotkey, OperatorNoID: fixture.authority.Expected.NoID}) || lease.Intent().ReplicaNoID == lease.Owner().OperatorNoID || len(owner.config.ActivationContexts) != 0 {
		t.Fatal("destination and original operator authority collapsed")
	}
	if err := lease.Start(true); err != nil {
		t.Fatal(err)
	}
}

// A historic permit is insufficient after its stable hotkey loses current
// native eligibility. Refresh retires the old generation and cancels its lease.
func TestValidatorUploadAdmissionCurrentPermitRevokesHistoricalEligibility(t *testing.T) {
	t.Parallel()
	fixture := newValidatorUploadAuthorityTestFixture(t)
	owner := validatorUploadAdmissionTestState(t, fixture)
	header, sessionHash, digest := validatorUploadAdmissionTestHeader(t, fixture, fixture.authority.Expected, 0x41, "current-api-client", []byte("object"))
	lease, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now)
	if err != nil {
		t.Fatal(err)
	}
	defer lease.Close()
	fixture.currentPermit = false
	if !fixture.native.permit {
		t.Fatal("historical permit prerequisite was changed")
	}
	if err := owner.refresh(t.Context(), fixture.now); err != nil {
		t.Fatal(err)
	}
	<-lease.Context().Done()
	if next, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now); err == nil || next != nil {
		if next != nil {
			next.Close()
		}
		t.Fatal("historical-only permit retained protected staging")
	}
}

// A stale current native provider cannot be refreshed by a live HTTP reply
// or a fresh EVM clock, and an old cache cannot outlive its admitted timestamp.
func TestValidatorUploadAdmissionRejectsStaleNativeAndEVMClocks(t *testing.T) {
	t.Parallel()
	for _, fault := range []string{"native-old", "native-future", "evm-old", "evm-future", "expired-cache"} {
		fixture := newValidatorUploadAuthorityTestFixture(t)
		owner := validatorUploadAdmissionTestState(t, fixture)
		header, sessionHash, digest := validatorUploadAdmissionTestHeader(t, fixture, fixture.authority.Expected, 0x41, "current-api-client", []byte("object"))
		now := fixture.now
		switch fault {
		case "native-old":
			fixture.currentMillis -= 60000
		case "native-future":
			fixture.currentMillis++
		case "evm-old":
			fixture.now = fixture.now.Add(-60 * time.Second)
		case "evm-future":
			fixture.now = fixture.now.Add(time.Second)
		case "expired-cache":
			now = now.Add(60 * time.Second)
		}
		if fault != "expired-cache" {
			err := owner.refresh(t.Context(), now)
			if err == nil {
				t.Fatalf("%s stale refresh was admitted", fault)
			}
			owner.invalidate(err)
		}
		if lease, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, now); err == nil || lease != nil {
			if lease != nil {
				lease.Close()
			}
			t.Fatalf("%s retained staging authority", fault)
		}
	}
}

// Every wrong supplied field fails before any additional RPC or active slot.
func TestValidatorUploadAdmissionRefusesForgedRefreshedAndMisbindingIntents(t *testing.T) {
	t.Parallel()
	fixture := newValidatorUploadAuthorityTestFixture(t)
	owner := validatorUploadAdmissionTestState(t, fixture)
	header, sessionHash, digest := validatorUploadAdmissionTestHeader(t, fixture, fixture.authority.Expected, 0x41, "old-api-client", []byte("object"))
	for _, fault := range []string{"credential", "content", "kind", "size", "forged", "activation", "destination", "expiry"} {
		candidate, credential, hash, kind, size := header, sessionHash, digest, byte(1), uint64(6)
		switch fault {
		case "credential":
			credential = sha256.Sum256([]byte("refreshed-api-client"))
		case "content":
			hash[0] ^= 1
		case "kind":
			kind = 2
		case "size":
			size++
		case "forged":
			value := []byte(candidate)
			value[len(value)/2] ^= 1
			candidate = string(value)
		default:
			intent, err := protocol.VerifyValidatorAttemptUploadHeader(header)
			if err != nil {
				t.Fatal(err)
			}
			switch fault {
			case "activation":
				intent.ActivationHash[0] ^= 1
			case "destination":
				intent.ReplicaNoID++
			case "expiry":
				intent.NotAfter = uint64(fixture.now.Unix())
			}
			candidate, err = intent.Sign(ed25519.NewKeyFromSeed(append([]byte{0x41}, make([]byte, 31)...)))
			if err != nil {
				t.Fatal(err)
			}
		}
		before := fixture.calls.Load()
		lease, err := owner.beginAt(t.Context(), candidate, credential, kind, hash, size, fixture.now)
		if err == nil || lease != nil || fixture.calls.Load() != before {
			if lease != nil {
				lease.Close()
			}
			t.Fatalf("%s invalid intent was admitted or dialed RPC: %v", fault, err)
		}
	}
	refreshed, newSession, _ := validatorUploadAdmissionTestHeader(t, fixture, fixture.authority.Expected, 0x41, "refreshed-api-client", []byte("object"))
	lease, err := owner.beginAt(t.Context(), refreshed, newSession, 1, digest, 6, fixture.now)
	if err != nil {
		t.Fatalf("real renewed-account consent was refused: %v", err)
	}
	defer lease.Close()
	oldIntent, _ := protocol.VerifyValidatorAttemptUploadHeader(header)
	oldObject, _ := oldIntent.ObjectReservationHash()
	newObject, _ := lease.Intent().ObjectReservationHash()
	if oldObject != newObject {
		t.Fatal("JWT refresh minted another protected object reservation")
	}
}

// Observed retries have a distinct active pool, so a held duplicate cannot
// occupy the fresh-object slot. Both pools remain nonblocking and finite.
func TestValidatorUploadAdmissionDuplicateSlotCannotBlockFreshObject(t *testing.T) {
	t.Parallel()
	fixture := newValidatorUploadAuthorityTestFixture(t)
	owner := validatorUploadAdmissionTestState(t, fixture)
	header, sessionHash, digest := validatorUploadAdmissionTestHeader(t, fixture, fixture.authority.Expected, 0x41, "current-api-client", []byte("object"))
	leases := make([]*ValidatorUploadLease, 0, 3)
	defer func() {
		for _, lease := range leases {
			lease.Close()
		}
	}()
	for index := range 3 {
		lease, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now)
		if err != nil {
			t.Fatal(err)
		}
		leases = append(leases, lease)
		err = lease.Start(index == 1)
		if index < 2 && err != nil {
			t.Fatalf("retry traffic denied the separate fresh slot: %v", err)
		}
		if index == 2 && err == nil {
			t.Fatal("duplicate active slot bound was bypassed")
		}
	}
}

// The old active slot is not replaced by an activation/VPK rotation. Redis
// receives the exact same stable owner key from both genuinely signed records.
func TestValidatorUploadAdmissionVPKRotationPreservesOwnerAndActiveMinima(t *testing.T) {
	t.Parallel()
	fixture := newValidatorUploadAuthorityTestFixture(t)
	owner := validatorUploadAdmissionTestState(t, fixture)
	header, sessionHash, digest := validatorUploadAdmissionTestHeader(t, fixture, fixture.authority.Expected, 0x41, "current-api-client", []byte("object"))
	prior, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now)
	if err != nil {
		t.Fatal(err)
	}
	defer prior.Close()
	if err := prior.Start(true); err != nil {
		t.Fatal(err)
	}
	key := ed25519.NewKeyFromSeed(append([]byte{0x42}, make([]byte, 31)...))
	record := fixture.authority.Expected
	copy(record.VPK[:], key[32:])
	fixture.publish(t, record, 1002, key)
	if err := owner.refresh(t.Context(), fixture.now); err != nil {
		t.Fatal(err)
	}
	<-prior.Context().Done()
	if old, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now); err == nil || old != nil {
		if old != nil {
			old.Close()
		}
		t.Fatal("superseded activation retained admission")
	}
	newHeader, newSession, newHash := validatorUploadAdmissionTestHeader(t, fixture, record, 0x42, "refreshed-api-client", []byte("next object"))
	current, err := owner.beginAt(t.Context(), newHeader, newSession, 1, newHash, 11, fixture.now)
	if err != nil {
		t.Fatal(err)
	}
	defer current.Close()
	if current.Owner() != prior.Owner() || len(owner.ownerSlots) != 1 || current.entry.slots != prior.entry.slots {
		t.Fatal("same hotkey rotation multiplied protected owner capacity")
	}
	if err := current.Start(true); err == nil {
		t.Fatal("new VPK bypassed the still-owned old fresh slot")
	}
	prior.Close()
	next, err := owner.beginAt(t.Context(), newHeader, newSession, 1, newHash, 11, fixture.now)
	if err != nil {
		t.Fatal(err)
	}
	defer next.Close()
	if err := next.Start(true); err != nil {
		t.Fatalf("joined old owner did not release rotated slot: %v", err)
	}
}

// Failed complete-discovery admission cannot leave the previous cache usable,
// even when its activation bytes themselves still match the approved runtime.
func TestValidatorUploadAdmissionIncompleteRefreshClearsAndCancelsLeases(t *testing.T) {
	t.Parallel()
	fixture := newValidatorUploadAuthorityTestFixture(t)
	owner := validatorUploadAdmissionTestState(t, fixture)
	header, sessionHash, digest := validatorUploadAdmissionTestHeader(t, fixture, fixture.authority.Expected, 0x41, "current-api-client", []byte("object"))
	lease, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now)
	if err != nil {
		t.Fatal(err)
	}
	defer lease.Close()
	fixture.fault = "null-events"
	err = owner.refresh(t.Context(), fixture.now)
	if err == nil {
		t.Fatal("incomplete event census was a successful refresh")
	}
	owner.invalidate(err)
	<-lease.Context().Done()
	if next, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now); err == nil || next != nil {
		if next != nil {
			next.Close()
		}
		t.Fatal("failed discovery preserved upload authority")
	}
}

// The public constructor starts its real owned loop. Shutdown interrupts the
// actual EVM read and joins it; no supplied historical-verdict callback exists.
func TestValidatorUploadAdmissionCloseJoinsActualRefresh(t *testing.T) {
	t.Parallel()
	fixture := newValidatorUploadAuthorityTestFixture(t)
	entered, left := make(chan struct{}), make(chan struct{})
	fixture.beforeCode = func(ctx context.Context) error { close(entered); defer close(left); <-ctx.Done(); return ctx.Err() }
	owner, err := NewValidatorUploadAdmission(t.Context(), fixture.chain, fixture.native.chain, fixture.config())
	if err != nil {
		t.Fatal(err)
	}
	defer owner.Close()
	<-entered
	owner.Close()
	<-left
	if owner.ctx.Err() == nil || len(owner.entries) != 0 {
		t.Fatal("closed cache retained a refresh owner or entry")
	}
	if err := owner.WaitReady(t.Context()); err == nil {
		t.Fatal("closed refresh owner reported readiness")
	}
}

// The current native reader runs after historical EVM authentication. Its
// real canonical callback forces a reorg before the cache can publish again.
func TestValidatorUploadAdmissionRechecksCanonicalEVMThroughCurrentNativeRead(t *testing.T) {
	t.Parallel()
	fixture := newValidatorUploadAuthorityTestFixture(t)
	owner := validatorUploadAdmissionTestState(t, fixture)
	header, sessionHash, digest := validatorUploadAdmissionTestHeader(t, fixture, fixture.authority.Expected, 0x41, "current-api-client", []byte("object"))
	lease, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now)
	if err != nil {
		t.Fatal(err)
	}
	defer lease.Close()
	fixture.currentCanonicalCalls = 0
	fixture.reorgAfterCurrentCanonical = true
	err = owner.refresh(t.Context(), fixture.now)
	if !fixture.observerReorg.Load() || err == nil {
		t.Fatal("cached hash identity concealed a reorg after current native eligibility")
	}
	owner.invalidate(err)
	<-lease.Context().Done()
	if next, err := owner.beginAt(t.Context(), header, sessionHash, 1, digest, 6, fixture.now); err == nil || next != nil {
		if next != nil {
			next.Close()
		}
		t.Fatal("reorged refresh retained protected staging authority")
	}
}
