package crv4

import (
	"errors"
	"testing"
	"time"
)

// Reveal-block vectors cross-checked against the reference implementation:
// the first three mirror bittensor-drand v2.0.0 epoch_schedule_vectors.rs;
// all expected values (including the extra scenarios) were generated by
// running the reference epoch_schedule.rs (copied verbatim into a Rust
// harness) — see crv4/README.md.
func TestPredictFirstRevealBlock(t *testing.T) {
	cases := []struct {
		name  string
		state EpochScheduleState
		rpe   uint64
		want  uint64
	}{
		{
			// Reference vector "cycle_reset": last=10, tempo=50 → the epoch
			// slot fires when blocks_since = block-10 >= 50, i.e. block 60.
			// Commit lands at block 11 (head+1) in epoch 0; target epoch =
			// 0+1; block 60 is the first block whose pre-run_coinbase epoch
			// is 1.
			name:  "cycle_reset",
			state: EpochScheduleState{LastEpochBlock: 10, Tempo: 50, CurrentBlock: 10},
			rpe:   1,
			want:  60,
		},
		{
			// Reference vector "pending_fires_before_auto": owner-triggered
			// epoch at 95 fires before the auto slot (80+20=100).
			name:  "pending_fires_before_auto",
			state: EpochScheduleState{LastEpochBlock: 80, PendingEpochAt: 95, Tempo: 20, CurrentBlock: 91},
			rpe:   1,
			want:  95,
		},
		{
			// bittensor-drand commit-epoch vector state: commit at block 121
			// belongs to epoch 0; target 1 fires at 100+50.
			name:  "mid_epoch",
			state: EpochScheduleState{LastEpochBlock: 100, Tempo: 50, CurrentBlock: 120},
			rpe:   1,
			want:  150,
		},
		{
			// Same state, reveal period 2 → one more full tempo: 200.
			name:  "mid_epoch_rpe2",
			state: EpochScheduleState{LastEpochBlock: 100, Tempo: 50, CurrentBlock: 120},
			rpe:   2,
			want:  200,
		},
		{
			// Nonzero epoch counter/blocks_since don't shift the schedule:
			// fires at 150 (epoch 4), 200 (5), 250 (6=3+3).
			name:  "mid_epoch_rpe3",
			state: EpochScheduleState{LastEpochBlock: 100, SubnetEpochIndex: 3, Tempo: 50, BlocksSinceLastStep: 5, CurrentBlock: 120},
			rpe:   3,
			want:  250,
		},
		{
			// Head at 149: the extrinsic lands exactly on the fire block 150
			// (100+50), so the commit belongs to epoch 10 (9+1 lookahead) and
			// reveals at the NEXT slot 200. Guards the
			// current_epoch_with_lookahead behavior.
			name:  "boundary_fire_at_extrinsic",
			state: EpochScheduleState{LastEpochBlock: 100, SubnetEpochIndex: 9, Tempo: 50, BlocksSinceLastStep: 49, CurrentBlock: 149},
			rpe:   1,
			want:  200,
		},
		{
			// pending_epoch_at already in the past (50 < 91): fires at the
			// extrinsic block 92 (commit epoch 3 = 2+1), which resets
			// last_epoch_block to 92; target epoch 4 fires at 92+20=112.
			name:  "pending_in_past",
			state: EpochScheduleState{LastEpochBlock: 80, PendingEpochAt: 50, SubnetEpochIndex: 2, Tempo: 20, BlocksSinceLastStep: 11, CurrentBlock: 91},
			rpe:   1,
			want:  112,
		},
		{
			// blocks_since_last_step > MAX_TEMPO(50400) safety net: fires at
			// the extrinsic block 1000011 (commit epoch 8), then the next
			// auto slot 1000011+360 = 1000371 is the reveal.
			name:  "since_step_overflow",
			state: EpochScheduleState{LastEpochBlock: 1_000_000, SubnetEpochIndex: 7, Tempo: 360, BlocksSinceLastStep: 50_401, CurrentBlock: 1_000_010},
			rpe:   1,
			want:  1_000_371,
		},
		{
			// Mainnet-shaped numbers: last=4919251, tempo=360 → slot at
			// 4919611.
			name:  "mainnet_like",
			state: EpochScheduleState{LastEpochBlock: 4_919_251, SubnetEpochIndex: 13_664, Tempo: 360, BlocksSinceLastStep: 100, CurrentBlock: 4_919_351},
			rpe:   1,
			want:  4_919_611,
		},
		{
			// Fast-blocks testnet-shaped: tempo 100, reveal period 6 →
			// 3100000 + 6*100 = 3100600.
			name:  "testnet_fastblocks",
			state: EpochScheduleState{LastEpochBlock: 3_100_000, SubnetEpochIndex: 31_000, Tempo: 100, BlocksSinceLastStep: 10, CurrentBlock: 3_100_010},
			rpe:   6,
			want:  3_100_600,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := PredictFirstRevealBlock(&tc.state, tc.rpe)
			if err != nil {
				t.Fatalf("PredictFirstRevealBlock: %v", err)
			}
			if got != tc.want {
				t.Errorf("reveal block = %d, want %d", got, tc.want)
			}
		})
	}
}

func TestPredictFirstRevealBlockTempoZero(t *testing.T) {
	state := EpochScheduleState{LastEpochBlock: 10, CurrentBlock: 10}
	if _, err := PredictFirstRevealBlock(&state, 1); !errors.Is(err, ErrTempoZero) {
		t.Errorf("err = %v, want ErrTempoZero", err)
	}
}

// TestRevealRound pins the full generate_commit_v2 round computation against
// reference outputs at a fixed wall clock (now = 1751500000):
//
//	round = floor((now + (reveal_block+3-current_block)*block_time - 1692803367)/3)
//
// mainnet_like:  ingest 4919614, 263 blocks * 12s = 3156s;
//
//	(1751503156-1692803367)/3 = 58699789/3 → 19566596
//
// testnet:       ingest 3100603, 593 blocks * 0.25s = 148.25s;
//
//	(1751500148.25-1692803367)/3 → 19565593
//
// cycle_reset:   ingest 63, 53 blocks * 12s = 636s;
//
//	(1751500636-1692803367)/3 = 58697269/3 → 19565756
func TestRevealRound(t *testing.T) {
	now := time.Unix(1_751_500_000, 0)
	cases := []struct {
		name       string
		state      EpochScheduleState
		rpe        uint64
		blockTime  float64
		wantRound  uint64
		wantReveal uint64
	}{
		{
			name:       "mainnet_like",
			state:      EpochScheduleState{LastEpochBlock: 4_919_251, SubnetEpochIndex: 13_664, Tempo: 360, BlocksSinceLastStep: 100, CurrentBlock: 4_919_351},
			rpe:        1,
			blockTime:  12.0,
			wantRound:  19_566_596,
			wantReveal: 4_919_611,
		},
		{
			name:       "testnet_fastblocks",
			state:      EpochScheduleState{LastEpochBlock: 3_100_000, SubnetEpochIndex: 31_000, Tempo: 100, BlocksSinceLastStep: 10, CurrentBlock: 3_100_010},
			rpe:        6,
			blockTime:  0.25,
			wantRound:  19_565_593,
			wantReveal: 3_100_600,
		},
		{
			name:       "cycle_reset",
			state:      EpochScheduleState{LastEpochBlock: 10, Tempo: 50, CurrentBlock: 10},
			rpe:        1,
			blockTime:  12.0,
			wantRound:  19_565_756,
			wantReveal: 60,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			round, reveal, err := RevealRound(now, &tc.state, tc.rpe, tc.blockTime)
			if err != nil {
				t.Fatalf("RevealRound: %v", err)
			}
			if round != tc.wantRound || reveal != tc.wantReveal {
				t.Errorf("got (round=%d, reveal=%d), want (round=%d, reveal=%d)", round, reveal, tc.wantRound, tc.wantReveal)
			}
		})
	}
}

// TestRevealRoundFloorsAtOne: times before drand genesis clamp to round 1
// (mirrors the reference `if reveal_round < 1 { 1 }`).
func TestRevealRoundFloorsAtOne(t *testing.T) {
	state := EpochScheduleState{LastEpochBlock: 10, Tempo: 50, CurrentBlock: 10}
	round, _, err := RevealRound(time.Unix(0, 0), &state, 1, 12.0)
	if err != nil {
		t.Fatalf("RevealRound: %v", err)
	}
	if round != 1 {
		t.Errorf("round = %d, want 1", round)
	}
}

func TestCurrentDrandRound(t *testing.T) {
	// At genesis, round 1 is published; each +3s adds one round.
	if got := CurrentDrandRound(time.Unix(int64(DrandGenesisTime), 0)); got != 1 {
		t.Errorf("round at genesis = %d, want 1", got)
	}
	if got := CurrentDrandRound(time.Unix(int64(DrandGenesisTime)+3*999, 0)); got != 1000 {
		t.Errorf("round at genesis+2997s = %d, want 1000", got)
	}
	if got := CurrentDrandRound(time.Unix(0, 0)); got != 0 {
		t.Errorf("round before genesis = %d, want 0", got)
	}
}

// TestScheduleSimulationInvariants: the reveal block always satisfies exact
// epoch equality (not >=), and never precedes the extrinsic block.
func TestScheduleSimulationInvariants(t *testing.T) {
	states := []EpochScheduleState{
		{LastEpochBlock: 10, Tempo: 50, CurrentBlock: 10},
		{LastEpochBlock: 100, SubnetEpochIndex: 9, Tempo: 50, BlocksSinceLastStep: 49, CurrentBlock: 149},
		{LastEpochBlock: 80, PendingEpochAt: 95, Tempo: 20, CurrentBlock: 91},
	}
	for _, s := range states {
		for rpe := uint64(1); rpe <= 3; rpe++ {
			reveal, err := PredictFirstRevealBlock(&s, rpe)
			if err != nil {
				t.Fatalf("PredictFirstRevealBlock: %v", err)
			}
			if reveal <= s.CurrentBlock {
				t.Errorf("reveal %d not after head %d", reveal, s.CurrentBlock)
			}
			// Walk the simulation and assert the target epoch is hit at
			// `reveal` and never earlier.
			extrinsicBlock := s.CurrentBlock + CommitInclusionBlockOffset
			commitEpoch := currentEpochPreRunCoinbase(&s, extrinsicBlock)
			target := commitEpoch + rpe
			post := s
			for b := extrinsicBlock; b < reveal; b++ {
				if currentEpochPreRunCoinbase(&post, b) == target {
					t.Errorf("target epoch hit early at block %d < %d", b, reveal)
				}
				post = simulateRunCoinbase(&post, b)
			}
			if currentEpochPreRunCoinbase(&post, reveal) != target {
				t.Errorf("target epoch not hit at reveal block %d", reveal)
			}
		}
	}
}
